/**************************************************************************
**
** Copyright (C) 2016 The DZH Company Ltd.
** Contact: http://www.gw.com.cn
**
** This file is part of the DZH Open Source Client.
**
** $DZH_BEGIN_LICENSE:LGPL21$
**
** GNU Lesser General Public License Usage
** This file may be used under the terms of the GNU Lesser
** General Public License version 2.1 or version 3 as published by the Free
** Software Foundation and appearing in the file LICENSE.LGPLv21 and
** LICENSE.LGPLv3 included in the packaging of this file. Please review the
** following information to ensure the GNU Lesser General Public License
** requirements will be met: https://www.gnu.org/licenses/lgpl.html and
** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
**
** $DZH_END_LICENSE$
**
**************************************************************************/

import QtQuick 2.0

/**
  * 定义沪深股列表的初始化数据
  * 默认100条数据
  */
ListModel {
    id: stocks
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}

    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}

    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}
    ListElement { Head:""; XuHao:0; Obj:""; ZhongWenJianCheng:""; ZuiXinJia:""; ZhangDie:""; ZhangFu:""; ChengJiaoLiang:""; HuanShou:""; XianShou:""; ChengJiaoE:""; FenZhongZhangFu5:""; ZuoShou:""; KaiPanJia:""; ZuiGaoJia:""; ZuiDiJia:""; HangYe:""; ShiYingLv:""; ShiJingLv:""; ShiXiaoLv:""; WeiTuoMaiRuJia1:""; WeiTuoMaiChuJia1:""; NeiPan:""; WaiPan:""; ZhenFu:""; LiangBi:""; JunJia:""; WeiBi:""; WeiCha:""; ChengJiaoBiShu:""; ChengJiaoFangXiang:""; ZongShiZhi:""; LiuTongShiZhi:"";}

}
