// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CldForecastsShuJu.proto

#ifndef PROTOBUF_CldForecastsShuJu_2eproto__INCLUDED
#define PROTOBUF_CldForecastsShuJu_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dzhyun {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_CldForecastsShuJu_2eproto();
void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

class GeGuTouZiYanBao;
class GeGuTouZiYanBaoOutPut;
class GeGuYeJiYuCe;
class GeGuYeJiYuCeData;
class GeGuYeJiYuCeOutPut;
class YiZhiXinTouZiPinJi;
class YiZhiXinTouZiPinJiOutPut;
class YiZhiXinYeJiYuCe;
class YiZhiXinYeJiYuCeOutPut;

// ===================================================================

class YiZhiXinYeJiYuCe : public ::google::protobuf::Message {
 public:
  YiZhiXinYeJiYuCe();
  virtual ~YiZhiXinYeJiYuCe();

  YiZhiXinYeJiYuCe(const YiZhiXinYeJiYuCe& from);

  inline YiZhiXinYeJiYuCe& operator=(const YiZhiXinYeJiYuCe& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const YiZhiXinYeJiYuCe& default_instance();

  void Swap(YiZhiXinYeJiYuCe* other);

  // implements Message ----------------------------------------------

  inline YiZhiXinYeJiYuCe* New() const { return New(NULL); }

  YiZhiXinYeJiYuCe* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const YiZhiXinYeJiYuCe& from);
  void MergeFrom(const YiZhiXinYeJiYuCe& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(YiZhiXinYeJiYuCe* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string baoGaoRiQi = 1;
  bool has_baogaoriqi() const;
  void clear_baogaoriqi();
  static const int kBaoGaoRiQiFieldNumber = 1;
  const ::std::string& baogaoriqi() const;
  void set_baogaoriqi(const ::std::string& value);
  void set_baogaoriqi(const char* value);
  void set_baogaoriqi(const char* value, size_t size);
  ::std::string* mutable_baogaoriqi();
  ::std::string* release_baogaoriqi();
  void set_allocated_baogaoriqi(::std::string* baogaoriqi);

  // required string yuCeNianDu = 2;
  bool has_yuceniandu() const;
  void clear_yuceniandu();
  static const int kYuCeNianDuFieldNumber = 2;
  const ::std::string& yuceniandu() const;
  void set_yuceniandu(const ::std::string& value);
  void set_yuceniandu(const char* value);
  void set_yuceniandu(const char* value, size_t size);
  ::std::string* mutable_yuceniandu();
  ::std::string* release_yuceniandu();
  void set_allocated_yuceniandu(::std::string* yuceniandu);

  // optional int64 jingLiRun = 3;
  bool has_jinglirun() const;
  void clear_jinglirun();
  static const int kJingLiRunFieldNumber = 3;
  ::google::protobuf::int64 jinglirun() const;
  void set_jinglirun(::google::protobuf::int64 value);

  // optional int64 meiGuShouYi = 4;
  bool has_meigushouyi() const;
  void clear_meigushouyi();
  static const int kMeiGuShouYiFieldNumber = 4;
  ::google::protobuf::int64 meigushouyi() const;
  void set_meigushouyi(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:dzhyun.YiZhiXinYeJiYuCe)
 private:
  inline void set_has_baogaoriqi();
  inline void clear_has_baogaoriqi();
  inline void set_has_yuceniandu();
  inline void clear_has_yuceniandu();
  inline void set_has_jinglirun();
  inline void clear_has_jinglirun();
  inline void set_has_meigushouyi();
  inline void clear_has_meigushouyi();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr baogaoriqi_;
  ::google::protobuf::internal::ArenaStringPtr yuceniandu_;
  ::google::protobuf::int64 jinglirun_;
  ::google::protobuf::int64 meigushouyi_;
  friend void  protobuf_AddDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

  void InitAsDefaultInstance();
  static YiZhiXinYeJiYuCe* default_instance_;
};
// -------------------------------------------------------------------

class YiZhiXinYeJiYuCeOutPut : public ::google::protobuf::Message {
 public:
  YiZhiXinYeJiYuCeOutPut();
  virtual ~YiZhiXinYeJiYuCeOutPut();

  YiZhiXinYeJiYuCeOutPut(const YiZhiXinYeJiYuCeOutPut& from);

  inline YiZhiXinYeJiYuCeOutPut& operator=(const YiZhiXinYeJiYuCeOutPut& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const YiZhiXinYeJiYuCeOutPut& default_instance();

  void Swap(YiZhiXinYeJiYuCeOutPut* other);

  // implements Message ----------------------------------------------

  inline YiZhiXinYeJiYuCeOutPut* New() const { return New(NULL); }

  YiZhiXinYeJiYuCeOutPut* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const YiZhiXinYeJiYuCeOutPut& from);
  void MergeFrom(const YiZhiXinYeJiYuCeOutPut& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(YiZhiXinYeJiYuCeOutPut* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Obj = 1;
  bool has_obj() const;
  void clear_obj();
  static const int kObjFieldNumber = 1;
  const ::std::string& obj() const;
  void set_obj(const ::std::string& value);
  void set_obj(const char* value);
  void set_obj(const char* value, size_t size);
  ::std::string* mutable_obj();
  ::std::string* release_obj();
  void set_allocated_obj(::std::string* obj);

  // repeated .dzhyun.YiZhiXinYeJiYuCe Data = 2;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::dzhyun::YiZhiXinYeJiYuCe& data(int index) const;
  ::dzhyun::YiZhiXinYeJiYuCe* mutable_data(int index);
  ::dzhyun::YiZhiXinYeJiYuCe* add_data();
  ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinYeJiYuCe >*
      mutable_data();
  const ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinYeJiYuCe >&
      data() const;

  // @@protoc_insertion_point(class_scope:dzhyun.YiZhiXinYeJiYuCeOutPut)
 private:
  inline void set_has_obj();
  inline void clear_has_obj();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr obj_;
  ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinYeJiYuCe > data_;
  friend void  protobuf_AddDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

  void InitAsDefaultInstance();
  static YiZhiXinYeJiYuCeOutPut* default_instance_;
};
// -------------------------------------------------------------------

class YiZhiXinTouZiPinJi : public ::google::protobuf::Message {
 public:
  YiZhiXinTouZiPinJi();
  virtual ~YiZhiXinTouZiPinJi();

  YiZhiXinTouZiPinJi(const YiZhiXinTouZiPinJi& from);

  inline YiZhiXinTouZiPinJi& operator=(const YiZhiXinTouZiPinJi& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const YiZhiXinTouZiPinJi& default_instance();

  void Swap(YiZhiXinTouZiPinJi* other);

  // implements Message ----------------------------------------------

  inline YiZhiXinTouZiPinJi* New() const { return New(NULL); }

  YiZhiXinTouZiPinJi* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const YiZhiXinTouZiPinJi& from);
  void MergeFrom(const YiZhiXinTouZiPinJi& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(YiZhiXinTouZiPinJi* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string pinJiRiQi = 1;
  bool has_pinjiriqi() const;
  void clear_pinjiriqi();
  static const int kPinJiRiQiFieldNumber = 1;
  const ::std::string& pinjiriqi() const;
  void set_pinjiriqi(const ::std::string& value);
  void set_pinjiriqi(const char* value);
  void set_pinjiriqi(const char* value, size_t size);
  ::std::string* mutable_pinjiriqi();
  ::std::string* release_pinjiriqi();
  void set_allocated_pinjiriqi(::std::string* pinjiriqi);

  // required string zhengTiPinJi = 2;
  bool has_zhengtipinji() const;
  void clear_zhengtipinji();
  static const int kZhengTiPinJiFieldNumber = 2;
  const ::std::string& zhengtipinji() const;
  void set_zhengtipinji(const ::std::string& value);
  void set_zhengtipinji(const char* value);
  void set_zhengtipinji(const char* value, size_t size);
  ::std::string* mutable_zhengtipinji();
  ::std::string* release_zhengtipinji();
  void set_allocated_zhengtipinji(::std::string* zhengtipinji);

  // @@protoc_insertion_point(class_scope:dzhyun.YiZhiXinTouZiPinJi)
 private:
  inline void set_has_pinjiriqi();
  inline void clear_has_pinjiriqi();
  inline void set_has_zhengtipinji();
  inline void clear_has_zhengtipinji();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr pinjiriqi_;
  ::google::protobuf::internal::ArenaStringPtr zhengtipinji_;
  friend void  protobuf_AddDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

  void InitAsDefaultInstance();
  static YiZhiXinTouZiPinJi* default_instance_;
};
// -------------------------------------------------------------------

class YiZhiXinTouZiPinJiOutPut : public ::google::protobuf::Message {
 public:
  YiZhiXinTouZiPinJiOutPut();
  virtual ~YiZhiXinTouZiPinJiOutPut();

  YiZhiXinTouZiPinJiOutPut(const YiZhiXinTouZiPinJiOutPut& from);

  inline YiZhiXinTouZiPinJiOutPut& operator=(const YiZhiXinTouZiPinJiOutPut& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const YiZhiXinTouZiPinJiOutPut& default_instance();

  void Swap(YiZhiXinTouZiPinJiOutPut* other);

  // implements Message ----------------------------------------------

  inline YiZhiXinTouZiPinJiOutPut* New() const { return New(NULL); }

  YiZhiXinTouZiPinJiOutPut* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const YiZhiXinTouZiPinJiOutPut& from);
  void MergeFrom(const YiZhiXinTouZiPinJiOutPut& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(YiZhiXinTouZiPinJiOutPut* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Obj = 1;
  bool has_obj() const;
  void clear_obj();
  static const int kObjFieldNumber = 1;
  const ::std::string& obj() const;
  void set_obj(const ::std::string& value);
  void set_obj(const char* value);
  void set_obj(const char* value, size_t size);
  ::std::string* mutable_obj();
  ::std::string* release_obj();
  void set_allocated_obj(::std::string* obj);

  // repeated .dzhyun.YiZhiXinTouZiPinJi Data = 2;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::dzhyun::YiZhiXinTouZiPinJi& data(int index) const;
  ::dzhyun::YiZhiXinTouZiPinJi* mutable_data(int index);
  ::dzhyun::YiZhiXinTouZiPinJi* add_data();
  ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinTouZiPinJi >*
      mutable_data();
  const ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinTouZiPinJi >&
      data() const;

  // @@protoc_insertion_point(class_scope:dzhyun.YiZhiXinTouZiPinJiOutPut)
 private:
  inline void set_has_obj();
  inline void clear_has_obj();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr obj_;
  ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinTouZiPinJi > data_;
  friend void  protobuf_AddDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

  void InitAsDefaultInstance();
  static YiZhiXinTouZiPinJiOutPut* default_instance_;
};
// -------------------------------------------------------------------

class GeGuYeJiYuCe : public ::google::protobuf::Message {
 public:
  GeGuYeJiYuCe();
  virtual ~GeGuYeJiYuCe();

  GeGuYeJiYuCe(const GeGuYeJiYuCe& from);

  inline GeGuYeJiYuCe& operator=(const GeGuYeJiYuCe& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GeGuYeJiYuCe& default_instance();

  void Swap(GeGuYeJiYuCe* other);

  // implements Message ----------------------------------------------

  inline GeGuYeJiYuCe* New() const { return New(NULL); }

  GeGuYeJiYuCe* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GeGuYeJiYuCe& from);
  void MergeFrom(const GeGuYeJiYuCe& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GeGuYeJiYuCe* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string yuCeNianDu = 1;
  bool has_yuceniandu() const;
  void clear_yuceniandu();
  static const int kYuCeNianDuFieldNumber = 1;
  const ::std::string& yuceniandu() const;
  void set_yuceniandu(const ::std::string& value);
  void set_yuceniandu(const char* value);
  void set_yuceniandu(const char* value, size_t size);
  ::std::string* mutable_yuceniandu();
  ::std::string* release_yuceniandu();
  void set_allocated_yuceniandu(::std::string* yuceniandu);

  // optional int64 meiGuShouYi = 2;
  bool has_meigushouyi() const;
  void clear_meigushouyi();
  static const int kMeiGuShouYiFieldNumber = 2;
  ::google::protobuf::int64 meigushouyi() const;
  void set_meigushouyi(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:dzhyun.GeGuYeJiYuCe)
 private:
  inline void set_has_yuceniandu();
  inline void clear_has_yuceniandu();
  inline void set_has_meigushouyi();
  inline void clear_has_meigushouyi();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr yuceniandu_;
  ::google::protobuf::int64 meigushouyi_;
  friend void  protobuf_AddDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

  void InitAsDefaultInstance();
  static GeGuYeJiYuCe* default_instance_;
};
// -------------------------------------------------------------------

class GeGuYeJiYuCeData : public ::google::protobuf::Message {
 public:
  GeGuYeJiYuCeData();
  virtual ~GeGuYeJiYuCeData();

  GeGuYeJiYuCeData(const GeGuYeJiYuCeData& from);

  inline GeGuYeJiYuCeData& operator=(const GeGuYeJiYuCeData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GeGuYeJiYuCeData& default_instance();

  void Swap(GeGuYeJiYuCeData* other);

  // implements Message ----------------------------------------------

  inline GeGuYeJiYuCeData* New() const { return New(NULL); }

  GeGuYeJiYuCeData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GeGuYeJiYuCeData& from);
  void MergeFrom(const GeGuYeJiYuCeData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GeGuYeJiYuCeData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string yanJiuJiGou = 1;
  bool has_yanjiujigou() const;
  void clear_yanjiujigou();
  static const int kYanJiuJiGouFieldNumber = 1;
  const ::std::string& yanjiujigou() const;
  void set_yanjiujigou(const ::std::string& value);
  void set_yanjiujigou(const char* value);
  void set_yanjiujigou(const char* value, size_t size);
  ::std::string* mutable_yanjiujigou();
  ::std::string* release_yanjiujigou();
  void set_allocated_yanjiujigou(::std::string* yanjiujigou);

  // required string baoGaoRiQi = 2;
  bool has_baogaoriqi() const;
  void clear_baogaoriqi();
  static const int kBaoGaoRiQiFieldNumber = 2;
  const ::std::string& baogaoriqi() const;
  void set_baogaoriqi(const ::std::string& value);
  void set_baogaoriqi(const char* value);
  void set_baogaoriqi(const char* value, size_t size);
  ::std::string* mutable_baogaoriqi();
  ::std::string* release_baogaoriqi();
  void set_allocated_baogaoriqi(::std::string* baogaoriqi);

  // repeated .dzhyun.GeGuYeJiYuCe data = 3;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::dzhyun::GeGuYeJiYuCe& data(int index) const;
  ::dzhyun::GeGuYeJiYuCe* mutable_data(int index);
  ::dzhyun::GeGuYeJiYuCe* add_data();
  ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCe >*
      mutable_data();
  const ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCe >&
      data() const;

  // @@protoc_insertion_point(class_scope:dzhyun.GeGuYeJiYuCeData)
 private:
  inline void set_has_yanjiujigou();
  inline void clear_has_yanjiujigou();
  inline void set_has_baogaoriqi();
  inline void clear_has_baogaoriqi();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr yanjiujigou_;
  ::google::protobuf::internal::ArenaStringPtr baogaoriqi_;
  ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCe > data_;
  friend void  protobuf_AddDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

  void InitAsDefaultInstance();
  static GeGuYeJiYuCeData* default_instance_;
};
// -------------------------------------------------------------------

class GeGuYeJiYuCeOutPut : public ::google::protobuf::Message {
 public:
  GeGuYeJiYuCeOutPut();
  virtual ~GeGuYeJiYuCeOutPut();

  GeGuYeJiYuCeOutPut(const GeGuYeJiYuCeOutPut& from);

  inline GeGuYeJiYuCeOutPut& operator=(const GeGuYeJiYuCeOutPut& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GeGuYeJiYuCeOutPut& default_instance();

  void Swap(GeGuYeJiYuCeOutPut* other);

  // implements Message ----------------------------------------------

  inline GeGuYeJiYuCeOutPut* New() const { return New(NULL); }

  GeGuYeJiYuCeOutPut* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GeGuYeJiYuCeOutPut& from);
  void MergeFrom(const GeGuYeJiYuCeOutPut& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GeGuYeJiYuCeOutPut* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Obj = 1;
  bool has_obj() const;
  void clear_obj();
  static const int kObjFieldNumber = 1;
  const ::std::string& obj() const;
  void set_obj(const ::std::string& value);
  void set_obj(const char* value);
  void set_obj(const char* value, size_t size);
  ::std::string* mutable_obj();
  ::std::string* release_obj();
  void set_allocated_obj(::std::string* obj);

  // repeated .dzhyun.GeGuYeJiYuCeData data = 2;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::dzhyun::GeGuYeJiYuCeData& data(int index) const;
  ::dzhyun::GeGuYeJiYuCeData* mutable_data(int index);
  ::dzhyun::GeGuYeJiYuCeData* add_data();
  ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCeData >*
      mutable_data();
  const ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCeData >&
      data() const;

  // @@protoc_insertion_point(class_scope:dzhyun.GeGuYeJiYuCeOutPut)
 private:
  inline void set_has_obj();
  inline void clear_has_obj();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr obj_;
  ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCeData > data_;
  friend void  protobuf_AddDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

  void InitAsDefaultInstance();
  static GeGuYeJiYuCeOutPut* default_instance_;
};
// -------------------------------------------------------------------

class GeGuTouZiYanBao : public ::google::protobuf::Message {
 public:
  GeGuTouZiYanBao();
  virtual ~GeGuTouZiYanBao();

  GeGuTouZiYanBao(const GeGuTouZiYanBao& from);

  inline GeGuTouZiYanBao& operator=(const GeGuTouZiYanBao& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GeGuTouZiYanBao& default_instance();

  void Swap(GeGuTouZiYanBao* other);

  // implements Message ----------------------------------------------

  inline GeGuTouZiYanBao* New() const { return New(NULL); }

  GeGuTouZiYanBao* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GeGuTouZiYanBao& from);
  void MergeFrom(const GeGuTouZiYanBao& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GeGuTouZiYanBao* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string baoGaoRiQi = 1;
  bool has_baogaoriqi() const;
  void clear_baogaoriqi();
  static const int kBaoGaoRiQiFieldNumber = 1;
  const ::std::string& baogaoriqi() const;
  void set_baogaoriqi(const ::std::string& value);
  void set_baogaoriqi(const char* value);
  void set_baogaoriqi(const char* value, size_t size);
  ::std::string* mutable_baogaoriqi();
  ::std::string* release_baogaoriqi();
  void set_allocated_baogaoriqi(::std::string* baogaoriqi);

  // optional string yanJiuJiGou = 2;
  bool has_yanjiujigou() const;
  void clear_yanjiujigou();
  static const int kYanJiuJiGouFieldNumber = 2;
  const ::std::string& yanjiujigou() const;
  void set_yanjiujigou(const ::std::string& value);
  void set_yanjiujigou(const char* value);
  void set_yanjiujigou(const char* value, size_t size);
  ::std::string* mutable_yanjiujigou();
  ::std::string* release_yanjiujigou();
  void set_allocated_yanjiujigou(::std::string* yanjiujigou);

  // optional string pinJiLeiBie = 3;
  bool has_pinjileibie() const;
  void clear_pinjileibie();
  static const int kPinJiLeiBieFieldNumber = 3;
  const ::std::string& pinjileibie() const;
  void set_pinjileibie(const ::std::string& value);
  void set_pinjileibie(const char* value);
  void set_pinjileibie(const char* value, size_t size);
  ::std::string* mutable_pinjileibie();
  ::std::string* release_pinjileibie();
  void set_allocated_pinjileibie(::std::string* pinjileibie);

  // optional string pinJiBianDong = 4;
  bool has_pinjibiandong() const;
  void clear_pinjibiandong();
  static const int kPinJiBianDongFieldNumber = 4;
  const ::std::string& pinjibiandong() const;
  void set_pinjibiandong(const ::std::string& value);
  void set_pinjibiandong(const char* value);
  void set_pinjibiandong(const char* value, size_t size);
  ::std::string* mutable_pinjibiandong();
  ::std::string* release_pinjibiandong();
  void set_allocated_pinjibiandong(::std::string* pinjibiandong);

  // optional string yanBaoBiaoTi = 5;
  bool has_yanbaobiaoti() const;
  void clear_yanbaobiaoti();
  static const int kYanBaoBiaoTiFieldNumber = 5;
  const ::std::string& yanbaobiaoti() const;
  void set_yanbaobiaoti(const ::std::string& value);
  void set_yanbaobiaoti(const char* value);
  void set_yanbaobiaoti(const char* value, size_t size);
  ::std::string* mutable_yanbaobiaoti();
  ::std::string* release_yanbaobiaoti();
  void set_allocated_yanbaobiaoti(::std::string* yanbaobiaoti);

  // optional string yanBaoNeiRong = 6;
  bool has_yanbaoneirong() const;
  void clear_yanbaoneirong();
  static const int kYanBaoNeiRongFieldNumber = 6;
  const ::std::string& yanbaoneirong() const;
  void set_yanbaoneirong(const ::std::string& value);
  void set_yanbaoneirong(const char* value);
  void set_yanbaoneirong(const char* value, size_t size);
  ::std::string* mutable_yanbaoneirong();
  ::std::string* release_yanbaoneirong();
  void set_allocated_yanbaoneirong(::std::string* yanbaoneirong);

  // optional string yanJiuZuoZhe = 7;
  bool has_yanjiuzuozhe() const;
  void clear_yanjiuzuozhe();
  static const int kYanJiuZuoZheFieldNumber = 7;
  const ::std::string& yanjiuzuozhe() const;
  void set_yanjiuzuozhe(const ::std::string& value);
  void set_yanjiuzuozhe(const char* value);
  void set_yanjiuzuozhe(const char* value, size_t size);
  ::std::string* mutable_yanjiuzuozhe();
  ::std::string* release_yanjiuzuozhe();
  void set_allocated_yanjiuzuozhe(::std::string* yanjiuzuozhe);

  // optional string muBiaoJiaGe = 8;
  bool has_mubiaojiage() const;
  void clear_mubiaojiage();
  static const int kMuBiaoJiaGeFieldNumber = 8;
  const ::std::string& mubiaojiage() const;
  void set_mubiaojiage(const ::std::string& value);
  void set_mubiaojiage(const char* value);
  void set_mubiaojiage(const char* value, size_t size);
  ::std::string* mutable_mubiaojiage();
  ::std::string* release_mubiaojiage();
  void set_allocated_mubiaojiage(::std::string* mubiaojiage);

  // @@protoc_insertion_point(class_scope:dzhyun.GeGuTouZiYanBao)
 private:
  inline void set_has_baogaoriqi();
  inline void clear_has_baogaoriqi();
  inline void set_has_yanjiujigou();
  inline void clear_has_yanjiujigou();
  inline void set_has_pinjileibie();
  inline void clear_has_pinjileibie();
  inline void set_has_pinjibiandong();
  inline void clear_has_pinjibiandong();
  inline void set_has_yanbaobiaoti();
  inline void clear_has_yanbaobiaoti();
  inline void set_has_yanbaoneirong();
  inline void clear_has_yanbaoneirong();
  inline void set_has_yanjiuzuozhe();
  inline void clear_has_yanjiuzuozhe();
  inline void set_has_mubiaojiage();
  inline void clear_has_mubiaojiage();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr baogaoriqi_;
  ::google::protobuf::internal::ArenaStringPtr yanjiujigou_;
  ::google::protobuf::internal::ArenaStringPtr pinjileibie_;
  ::google::protobuf::internal::ArenaStringPtr pinjibiandong_;
  ::google::protobuf::internal::ArenaStringPtr yanbaobiaoti_;
  ::google::protobuf::internal::ArenaStringPtr yanbaoneirong_;
  ::google::protobuf::internal::ArenaStringPtr yanjiuzuozhe_;
  ::google::protobuf::internal::ArenaStringPtr mubiaojiage_;
  friend void  protobuf_AddDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

  void InitAsDefaultInstance();
  static GeGuTouZiYanBao* default_instance_;
};
// -------------------------------------------------------------------

class GeGuTouZiYanBaoOutPut : public ::google::protobuf::Message {
 public:
  GeGuTouZiYanBaoOutPut();
  virtual ~GeGuTouZiYanBaoOutPut();

  GeGuTouZiYanBaoOutPut(const GeGuTouZiYanBaoOutPut& from);

  inline GeGuTouZiYanBaoOutPut& operator=(const GeGuTouZiYanBaoOutPut& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GeGuTouZiYanBaoOutPut& default_instance();

  void Swap(GeGuTouZiYanBaoOutPut* other);

  // implements Message ----------------------------------------------

  inline GeGuTouZiYanBaoOutPut* New() const { return New(NULL); }

  GeGuTouZiYanBaoOutPut* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GeGuTouZiYanBaoOutPut& from);
  void MergeFrom(const GeGuTouZiYanBaoOutPut& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GeGuTouZiYanBaoOutPut* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Obj = 1;
  bool has_obj() const;
  void clear_obj();
  static const int kObjFieldNumber = 1;
  const ::std::string& obj() const;
  void set_obj(const ::std::string& value);
  void set_obj(const char* value);
  void set_obj(const char* value, size_t size);
  ::std::string* mutable_obj();
  ::std::string* release_obj();
  void set_allocated_obj(::std::string* obj);

  // repeated .dzhyun.GeGuTouZiYanBao Data = 2;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::dzhyun::GeGuTouZiYanBao& data(int index) const;
  ::dzhyun::GeGuTouZiYanBao* mutable_data(int index);
  ::dzhyun::GeGuTouZiYanBao* add_data();
  ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuTouZiYanBao >*
      mutable_data();
  const ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuTouZiYanBao >&
      data() const;

  // @@protoc_insertion_point(class_scope:dzhyun.GeGuTouZiYanBaoOutPut)
 private:
  inline void set_has_obj();
  inline void clear_has_obj();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr obj_;
  ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuTouZiYanBao > data_;
  friend void  protobuf_AddDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_AssignDesc_CldForecastsShuJu_2eproto();
  friend void protobuf_ShutdownFile_CldForecastsShuJu_2eproto();

  void InitAsDefaultInstance();
  static GeGuTouZiYanBaoOutPut* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// YiZhiXinYeJiYuCe

// required string baoGaoRiQi = 1;
inline bool YiZhiXinYeJiYuCe::has_baogaoriqi() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void YiZhiXinYeJiYuCe::set_has_baogaoriqi() {
  _has_bits_[0] |= 0x00000001u;
}
inline void YiZhiXinYeJiYuCe::clear_has_baogaoriqi() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void YiZhiXinYeJiYuCe::clear_baogaoriqi() {
  baogaoriqi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_baogaoriqi();
}
inline const ::std::string& YiZhiXinYeJiYuCe::baogaoriqi() const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinYeJiYuCe.baoGaoRiQi)
  return baogaoriqi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinYeJiYuCe::set_baogaoriqi(const ::std::string& value) {
  set_has_baogaoriqi();
  baogaoriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.YiZhiXinYeJiYuCe.baoGaoRiQi)
}
inline void YiZhiXinYeJiYuCe::set_baogaoriqi(const char* value) {
  set_has_baogaoriqi();
  baogaoriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.YiZhiXinYeJiYuCe.baoGaoRiQi)
}
inline void YiZhiXinYeJiYuCe::set_baogaoriqi(const char* value, size_t size) {
  set_has_baogaoriqi();
  baogaoriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.YiZhiXinYeJiYuCe.baoGaoRiQi)
}
inline ::std::string* YiZhiXinYeJiYuCe::mutable_baogaoriqi() {
  set_has_baogaoriqi();
  // @@protoc_insertion_point(field_mutable:dzhyun.YiZhiXinYeJiYuCe.baoGaoRiQi)
  return baogaoriqi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* YiZhiXinYeJiYuCe::release_baogaoriqi() {
  // @@protoc_insertion_point(field_release:dzhyun.YiZhiXinYeJiYuCe.baoGaoRiQi)
  clear_has_baogaoriqi();
  return baogaoriqi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinYeJiYuCe::set_allocated_baogaoriqi(::std::string* baogaoriqi) {
  if (baogaoriqi != NULL) {
    set_has_baogaoriqi();
  } else {
    clear_has_baogaoriqi();
  }
  baogaoriqi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), baogaoriqi);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.YiZhiXinYeJiYuCe.baoGaoRiQi)
}

// required string yuCeNianDu = 2;
inline bool YiZhiXinYeJiYuCe::has_yuceniandu() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void YiZhiXinYeJiYuCe::set_has_yuceniandu() {
  _has_bits_[0] |= 0x00000002u;
}
inline void YiZhiXinYeJiYuCe::clear_has_yuceniandu() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void YiZhiXinYeJiYuCe::clear_yuceniandu() {
  yuceniandu_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_yuceniandu();
}
inline const ::std::string& YiZhiXinYeJiYuCe::yuceniandu() const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinYeJiYuCe.yuCeNianDu)
  return yuceniandu_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinYeJiYuCe::set_yuceniandu(const ::std::string& value) {
  set_has_yuceniandu();
  yuceniandu_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.YiZhiXinYeJiYuCe.yuCeNianDu)
}
inline void YiZhiXinYeJiYuCe::set_yuceniandu(const char* value) {
  set_has_yuceniandu();
  yuceniandu_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.YiZhiXinYeJiYuCe.yuCeNianDu)
}
inline void YiZhiXinYeJiYuCe::set_yuceniandu(const char* value, size_t size) {
  set_has_yuceniandu();
  yuceniandu_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.YiZhiXinYeJiYuCe.yuCeNianDu)
}
inline ::std::string* YiZhiXinYeJiYuCe::mutable_yuceniandu() {
  set_has_yuceniandu();
  // @@protoc_insertion_point(field_mutable:dzhyun.YiZhiXinYeJiYuCe.yuCeNianDu)
  return yuceniandu_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* YiZhiXinYeJiYuCe::release_yuceniandu() {
  // @@protoc_insertion_point(field_release:dzhyun.YiZhiXinYeJiYuCe.yuCeNianDu)
  clear_has_yuceniandu();
  return yuceniandu_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinYeJiYuCe::set_allocated_yuceniandu(::std::string* yuceniandu) {
  if (yuceniandu != NULL) {
    set_has_yuceniandu();
  } else {
    clear_has_yuceniandu();
  }
  yuceniandu_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), yuceniandu);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.YiZhiXinYeJiYuCe.yuCeNianDu)
}

// optional int64 jingLiRun = 3;
inline bool YiZhiXinYeJiYuCe::has_jinglirun() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void YiZhiXinYeJiYuCe::set_has_jinglirun() {
  _has_bits_[0] |= 0x00000004u;
}
inline void YiZhiXinYeJiYuCe::clear_has_jinglirun() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void YiZhiXinYeJiYuCe::clear_jinglirun() {
  jinglirun_ = GOOGLE_LONGLONG(0);
  clear_has_jinglirun();
}
inline ::google::protobuf::int64 YiZhiXinYeJiYuCe::jinglirun() const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinYeJiYuCe.jingLiRun)
  return jinglirun_;
}
inline void YiZhiXinYeJiYuCe::set_jinglirun(::google::protobuf::int64 value) {
  set_has_jinglirun();
  jinglirun_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.YiZhiXinYeJiYuCe.jingLiRun)
}

// optional int64 meiGuShouYi = 4;
inline bool YiZhiXinYeJiYuCe::has_meigushouyi() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void YiZhiXinYeJiYuCe::set_has_meigushouyi() {
  _has_bits_[0] |= 0x00000008u;
}
inline void YiZhiXinYeJiYuCe::clear_has_meigushouyi() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void YiZhiXinYeJiYuCe::clear_meigushouyi() {
  meigushouyi_ = GOOGLE_LONGLONG(0);
  clear_has_meigushouyi();
}
inline ::google::protobuf::int64 YiZhiXinYeJiYuCe::meigushouyi() const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinYeJiYuCe.meiGuShouYi)
  return meigushouyi_;
}
inline void YiZhiXinYeJiYuCe::set_meigushouyi(::google::protobuf::int64 value) {
  set_has_meigushouyi();
  meigushouyi_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.YiZhiXinYeJiYuCe.meiGuShouYi)
}

// -------------------------------------------------------------------

// YiZhiXinYeJiYuCeOutPut

// required string Obj = 1;
inline bool YiZhiXinYeJiYuCeOutPut::has_obj() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void YiZhiXinYeJiYuCeOutPut::set_has_obj() {
  _has_bits_[0] |= 0x00000001u;
}
inline void YiZhiXinYeJiYuCeOutPut::clear_has_obj() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void YiZhiXinYeJiYuCeOutPut::clear_obj() {
  obj_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_obj();
}
inline const ::std::string& YiZhiXinYeJiYuCeOutPut::obj() const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinYeJiYuCeOutPut.Obj)
  return obj_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinYeJiYuCeOutPut::set_obj(const ::std::string& value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.YiZhiXinYeJiYuCeOutPut.Obj)
}
inline void YiZhiXinYeJiYuCeOutPut::set_obj(const char* value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.YiZhiXinYeJiYuCeOutPut.Obj)
}
inline void YiZhiXinYeJiYuCeOutPut::set_obj(const char* value, size_t size) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.YiZhiXinYeJiYuCeOutPut.Obj)
}
inline ::std::string* YiZhiXinYeJiYuCeOutPut::mutable_obj() {
  set_has_obj();
  // @@protoc_insertion_point(field_mutable:dzhyun.YiZhiXinYeJiYuCeOutPut.Obj)
  return obj_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* YiZhiXinYeJiYuCeOutPut::release_obj() {
  // @@protoc_insertion_point(field_release:dzhyun.YiZhiXinYeJiYuCeOutPut.Obj)
  clear_has_obj();
  return obj_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinYeJiYuCeOutPut::set_allocated_obj(::std::string* obj) {
  if (obj != NULL) {
    set_has_obj();
  } else {
    clear_has_obj();
  }
  obj_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), obj);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.YiZhiXinYeJiYuCeOutPut.Obj)
}

// repeated .dzhyun.YiZhiXinYeJiYuCe Data = 2;
inline int YiZhiXinYeJiYuCeOutPut::data_size() const {
  return data_.size();
}
inline void YiZhiXinYeJiYuCeOutPut::clear_data() {
  data_.Clear();
}
inline const ::dzhyun::YiZhiXinYeJiYuCe& YiZhiXinYeJiYuCeOutPut::data(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinYeJiYuCeOutPut.Data)
  return data_.Get(index);
}
inline ::dzhyun::YiZhiXinYeJiYuCe* YiZhiXinYeJiYuCeOutPut::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.YiZhiXinYeJiYuCeOutPut.Data)
  return data_.Mutable(index);
}
inline ::dzhyun::YiZhiXinYeJiYuCe* YiZhiXinYeJiYuCeOutPut::add_data() {
  // @@protoc_insertion_point(field_add:dzhyun.YiZhiXinYeJiYuCeOutPut.Data)
  return data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinYeJiYuCe >*
YiZhiXinYeJiYuCeOutPut::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.YiZhiXinYeJiYuCeOutPut.Data)
  return &data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinYeJiYuCe >&
YiZhiXinYeJiYuCeOutPut::data() const {
  // @@protoc_insertion_point(field_list:dzhyun.YiZhiXinYeJiYuCeOutPut.Data)
  return data_;
}

// -------------------------------------------------------------------

// YiZhiXinTouZiPinJi

// required string pinJiRiQi = 1;
inline bool YiZhiXinTouZiPinJi::has_pinjiriqi() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void YiZhiXinTouZiPinJi::set_has_pinjiriqi() {
  _has_bits_[0] |= 0x00000001u;
}
inline void YiZhiXinTouZiPinJi::clear_has_pinjiriqi() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void YiZhiXinTouZiPinJi::clear_pinjiriqi() {
  pinjiriqi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_pinjiriqi();
}
inline const ::std::string& YiZhiXinTouZiPinJi::pinjiriqi() const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinTouZiPinJi.pinJiRiQi)
  return pinjiriqi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinTouZiPinJi::set_pinjiriqi(const ::std::string& value) {
  set_has_pinjiriqi();
  pinjiriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.YiZhiXinTouZiPinJi.pinJiRiQi)
}
inline void YiZhiXinTouZiPinJi::set_pinjiriqi(const char* value) {
  set_has_pinjiriqi();
  pinjiriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.YiZhiXinTouZiPinJi.pinJiRiQi)
}
inline void YiZhiXinTouZiPinJi::set_pinjiriqi(const char* value, size_t size) {
  set_has_pinjiriqi();
  pinjiriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.YiZhiXinTouZiPinJi.pinJiRiQi)
}
inline ::std::string* YiZhiXinTouZiPinJi::mutable_pinjiriqi() {
  set_has_pinjiriqi();
  // @@protoc_insertion_point(field_mutable:dzhyun.YiZhiXinTouZiPinJi.pinJiRiQi)
  return pinjiriqi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* YiZhiXinTouZiPinJi::release_pinjiriqi() {
  // @@protoc_insertion_point(field_release:dzhyun.YiZhiXinTouZiPinJi.pinJiRiQi)
  clear_has_pinjiriqi();
  return pinjiriqi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinTouZiPinJi::set_allocated_pinjiriqi(::std::string* pinjiriqi) {
  if (pinjiriqi != NULL) {
    set_has_pinjiriqi();
  } else {
    clear_has_pinjiriqi();
  }
  pinjiriqi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pinjiriqi);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.YiZhiXinTouZiPinJi.pinJiRiQi)
}

// required string zhengTiPinJi = 2;
inline bool YiZhiXinTouZiPinJi::has_zhengtipinji() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void YiZhiXinTouZiPinJi::set_has_zhengtipinji() {
  _has_bits_[0] |= 0x00000002u;
}
inline void YiZhiXinTouZiPinJi::clear_has_zhengtipinji() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void YiZhiXinTouZiPinJi::clear_zhengtipinji() {
  zhengtipinji_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_zhengtipinji();
}
inline const ::std::string& YiZhiXinTouZiPinJi::zhengtipinji() const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinTouZiPinJi.zhengTiPinJi)
  return zhengtipinji_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinTouZiPinJi::set_zhengtipinji(const ::std::string& value) {
  set_has_zhengtipinji();
  zhengtipinji_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.YiZhiXinTouZiPinJi.zhengTiPinJi)
}
inline void YiZhiXinTouZiPinJi::set_zhengtipinji(const char* value) {
  set_has_zhengtipinji();
  zhengtipinji_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.YiZhiXinTouZiPinJi.zhengTiPinJi)
}
inline void YiZhiXinTouZiPinJi::set_zhengtipinji(const char* value, size_t size) {
  set_has_zhengtipinji();
  zhengtipinji_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.YiZhiXinTouZiPinJi.zhengTiPinJi)
}
inline ::std::string* YiZhiXinTouZiPinJi::mutable_zhengtipinji() {
  set_has_zhengtipinji();
  // @@protoc_insertion_point(field_mutable:dzhyun.YiZhiXinTouZiPinJi.zhengTiPinJi)
  return zhengtipinji_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* YiZhiXinTouZiPinJi::release_zhengtipinji() {
  // @@protoc_insertion_point(field_release:dzhyun.YiZhiXinTouZiPinJi.zhengTiPinJi)
  clear_has_zhengtipinji();
  return zhengtipinji_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinTouZiPinJi::set_allocated_zhengtipinji(::std::string* zhengtipinji) {
  if (zhengtipinji != NULL) {
    set_has_zhengtipinji();
  } else {
    clear_has_zhengtipinji();
  }
  zhengtipinji_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), zhengtipinji);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.YiZhiXinTouZiPinJi.zhengTiPinJi)
}

// -------------------------------------------------------------------

// YiZhiXinTouZiPinJiOutPut

// required string Obj = 1;
inline bool YiZhiXinTouZiPinJiOutPut::has_obj() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void YiZhiXinTouZiPinJiOutPut::set_has_obj() {
  _has_bits_[0] |= 0x00000001u;
}
inline void YiZhiXinTouZiPinJiOutPut::clear_has_obj() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void YiZhiXinTouZiPinJiOutPut::clear_obj() {
  obj_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_obj();
}
inline const ::std::string& YiZhiXinTouZiPinJiOutPut::obj() const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinTouZiPinJiOutPut.Obj)
  return obj_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinTouZiPinJiOutPut::set_obj(const ::std::string& value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.YiZhiXinTouZiPinJiOutPut.Obj)
}
inline void YiZhiXinTouZiPinJiOutPut::set_obj(const char* value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.YiZhiXinTouZiPinJiOutPut.Obj)
}
inline void YiZhiXinTouZiPinJiOutPut::set_obj(const char* value, size_t size) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.YiZhiXinTouZiPinJiOutPut.Obj)
}
inline ::std::string* YiZhiXinTouZiPinJiOutPut::mutable_obj() {
  set_has_obj();
  // @@protoc_insertion_point(field_mutable:dzhyun.YiZhiXinTouZiPinJiOutPut.Obj)
  return obj_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* YiZhiXinTouZiPinJiOutPut::release_obj() {
  // @@protoc_insertion_point(field_release:dzhyun.YiZhiXinTouZiPinJiOutPut.Obj)
  clear_has_obj();
  return obj_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void YiZhiXinTouZiPinJiOutPut::set_allocated_obj(::std::string* obj) {
  if (obj != NULL) {
    set_has_obj();
  } else {
    clear_has_obj();
  }
  obj_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), obj);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.YiZhiXinTouZiPinJiOutPut.Obj)
}

// repeated .dzhyun.YiZhiXinTouZiPinJi Data = 2;
inline int YiZhiXinTouZiPinJiOutPut::data_size() const {
  return data_.size();
}
inline void YiZhiXinTouZiPinJiOutPut::clear_data() {
  data_.Clear();
}
inline const ::dzhyun::YiZhiXinTouZiPinJi& YiZhiXinTouZiPinJiOutPut::data(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.YiZhiXinTouZiPinJiOutPut.Data)
  return data_.Get(index);
}
inline ::dzhyun::YiZhiXinTouZiPinJi* YiZhiXinTouZiPinJiOutPut::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.YiZhiXinTouZiPinJiOutPut.Data)
  return data_.Mutable(index);
}
inline ::dzhyun::YiZhiXinTouZiPinJi* YiZhiXinTouZiPinJiOutPut::add_data() {
  // @@protoc_insertion_point(field_add:dzhyun.YiZhiXinTouZiPinJiOutPut.Data)
  return data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinTouZiPinJi >*
YiZhiXinTouZiPinJiOutPut::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.YiZhiXinTouZiPinJiOutPut.Data)
  return &data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::dzhyun::YiZhiXinTouZiPinJi >&
YiZhiXinTouZiPinJiOutPut::data() const {
  // @@protoc_insertion_point(field_list:dzhyun.YiZhiXinTouZiPinJiOutPut.Data)
  return data_;
}

// -------------------------------------------------------------------

// GeGuYeJiYuCe

// required string yuCeNianDu = 1;
inline bool GeGuYeJiYuCe::has_yuceniandu() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GeGuYeJiYuCe::set_has_yuceniandu() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GeGuYeJiYuCe::clear_has_yuceniandu() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GeGuYeJiYuCe::clear_yuceniandu() {
  yuceniandu_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_yuceniandu();
}
inline const ::std::string& GeGuYeJiYuCe::yuceniandu() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuYeJiYuCe.yuCeNianDu)
  return yuceniandu_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuYeJiYuCe::set_yuceniandu(const ::std::string& value) {
  set_has_yuceniandu();
  yuceniandu_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuYeJiYuCe.yuCeNianDu)
}
inline void GeGuYeJiYuCe::set_yuceniandu(const char* value) {
  set_has_yuceniandu();
  yuceniandu_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuYeJiYuCe.yuCeNianDu)
}
inline void GeGuYeJiYuCe::set_yuceniandu(const char* value, size_t size) {
  set_has_yuceniandu();
  yuceniandu_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuYeJiYuCe.yuCeNianDu)
}
inline ::std::string* GeGuYeJiYuCe::mutable_yuceniandu() {
  set_has_yuceniandu();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuYeJiYuCe.yuCeNianDu)
  return yuceniandu_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuYeJiYuCe::release_yuceniandu() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuYeJiYuCe.yuCeNianDu)
  clear_has_yuceniandu();
  return yuceniandu_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuYeJiYuCe::set_allocated_yuceniandu(::std::string* yuceniandu) {
  if (yuceniandu != NULL) {
    set_has_yuceniandu();
  } else {
    clear_has_yuceniandu();
  }
  yuceniandu_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), yuceniandu);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuYeJiYuCe.yuCeNianDu)
}

// optional int64 meiGuShouYi = 2;
inline bool GeGuYeJiYuCe::has_meigushouyi() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GeGuYeJiYuCe::set_has_meigushouyi() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GeGuYeJiYuCe::clear_has_meigushouyi() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GeGuYeJiYuCe::clear_meigushouyi() {
  meigushouyi_ = GOOGLE_LONGLONG(0);
  clear_has_meigushouyi();
}
inline ::google::protobuf::int64 GeGuYeJiYuCe::meigushouyi() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuYeJiYuCe.meiGuShouYi)
  return meigushouyi_;
}
inline void GeGuYeJiYuCe::set_meigushouyi(::google::protobuf::int64 value) {
  set_has_meigushouyi();
  meigushouyi_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.GeGuYeJiYuCe.meiGuShouYi)
}

// -------------------------------------------------------------------

// GeGuYeJiYuCeData

// required string yanJiuJiGou = 1;
inline bool GeGuYeJiYuCeData::has_yanjiujigou() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GeGuYeJiYuCeData::set_has_yanjiujigou() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GeGuYeJiYuCeData::clear_has_yanjiujigou() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GeGuYeJiYuCeData::clear_yanjiujigou() {
  yanjiujigou_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_yanjiujigou();
}
inline const ::std::string& GeGuYeJiYuCeData::yanjiujigou() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuYeJiYuCeData.yanJiuJiGou)
  return yanjiujigou_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuYeJiYuCeData::set_yanjiujigou(const ::std::string& value) {
  set_has_yanjiujigou();
  yanjiujigou_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuYeJiYuCeData.yanJiuJiGou)
}
inline void GeGuYeJiYuCeData::set_yanjiujigou(const char* value) {
  set_has_yanjiujigou();
  yanjiujigou_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuYeJiYuCeData.yanJiuJiGou)
}
inline void GeGuYeJiYuCeData::set_yanjiujigou(const char* value, size_t size) {
  set_has_yanjiujigou();
  yanjiujigou_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuYeJiYuCeData.yanJiuJiGou)
}
inline ::std::string* GeGuYeJiYuCeData::mutable_yanjiujigou() {
  set_has_yanjiujigou();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuYeJiYuCeData.yanJiuJiGou)
  return yanjiujigou_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuYeJiYuCeData::release_yanjiujigou() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuYeJiYuCeData.yanJiuJiGou)
  clear_has_yanjiujigou();
  return yanjiujigou_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuYeJiYuCeData::set_allocated_yanjiujigou(::std::string* yanjiujigou) {
  if (yanjiujigou != NULL) {
    set_has_yanjiujigou();
  } else {
    clear_has_yanjiujigou();
  }
  yanjiujigou_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), yanjiujigou);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuYeJiYuCeData.yanJiuJiGou)
}

// required string baoGaoRiQi = 2;
inline bool GeGuYeJiYuCeData::has_baogaoriqi() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GeGuYeJiYuCeData::set_has_baogaoriqi() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GeGuYeJiYuCeData::clear_has_baogaoriqi() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GeGuYeJiYuCeData::clear_baogaoriqi() {
  baogaoriqi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_baogaoriqi();
}
inline const ::std::string& GeGuYeJiYuCeData::baogaoriqi() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuYeJiYuCeData.baoGaoRiQi)
  return baogaoriqi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuYeJiYuCeData::set_baogaoriqi(const ::std::string& value) {
  set_has_baogaoriqi();
  baogaoriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuYeJiYuCeData.baoGaoRiQi)
}
inline void GeGuYeJiYuCeData::set_baogaoriqi(const char* value) {
  set_has_baogaoriqi();
  baogaoriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuYeJiYuCeData.baoGaoRiQi)
}
inline void GeGuYeJiYuCeData::set_baogaoriqi(const char* value, size_t size) {
  set_has_baogaoriqi();
  baogaoriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuYeJiYuCeData.baoGaoRiQi)
}
inline ::std::string* GeGuYeJiYuCeData::mutable_baogaoriqi() {
  set_has_baogaoriqi();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuYeJiYuCeData.baoGaoRiQi)
  return baogaoriqi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuYeJiYuCeData::release_baogaoriqi() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuYeJiYuCeData.baoGaoRiQi)
  clear_has_baogaoriqi();
  return baogaoriqi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuYeJiYuCeData::set_allocated_baogaoriqi(::std::string* baogaoriqi) {
  if (baogaoriqi != NULL) {
    set_has_baogaoriqi();
  } else {
    clear_has_baogaoriqi();
  }
  baogaoriqi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), baogaoriqi);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuYeJiYuCeData.baoGaoRiQi)
}

// repeated .dzhyun.GeGuYeJiYuCe data = 3;
inline int GeGuYeJiYuCeData::data_size() const {
  return data_.size();
}
inline void GeGuYeJiYuCeData::clear_data() {
  data_.Clear();
}
inline const ::dzhyun::GeGuYeJiYuCe& GeGuYeJiYuCeData::data(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuYeJiYuCeData.data)
  return data_.Get(index);
}
inline ::dzhyun::GeGuYeJiYuCe* GeGuYeJiYuCeData::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuYeJiYuCeData.data)
  return data_.Mutable(index);
}
inline ::dzhyun::GeGuYeJiYuCe* GeGuYeJiYuCeData::add_data() {
  // @@protoc_insertion_point(field_add:dzhyun.GeGuYeJiYuCeData.data)
  return data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCe >*
GeGuYeJiYuCeData::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.GeGuYeJiYuCeData.data)
  return &data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCe >&
GeGuYeJiYuCeData::data() const {
  // @@protoc_insertion_point(field_list:dzhyun.GeGuYeJiYuCeData.data)
  return data_;
}

// -------------------------------------------------------------------

// GeGuYeJiYuCeOutPut

// required string Obj = 1;
inline bool GeGuYeJiYuCeOutPut::has_obj() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GeGuYeJiYuCeOutPut::set_has_obj() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GeGuYeJiYuCeOutPut::clear_has_obj() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GeGuYeJiYuCeOutPut::clear_obj() {
  obj_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_obj();
}
inline const ::std::string& GeGuYeJiYuCeOutPut::obj() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuYeJiYuCeOutPut.Obj)
  return obj_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuYeJiYuCeOutPut::set_obj(const ::std::string& value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuYeJiYuCeOutPut.Obj)
}
inline void GeGuYeJiYuCeOutPut::set_obj(const char* value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuYeJiYuCeOutPut.Obj)
}
inline void GeGuYeJiYuCeOutPut::set_obj(const char* value, size_t size) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuYeJiYuCeOutPut.Obj)
}
inline ::std::string* GeGuYeJiYuCeOutPut::mutable_obj() {
  set_has_obj();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuYeJiYuCeOutPut.Obj)
  return obj_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuYeJiYuCeOutPut::release_obj() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuYeJiYuCeOutPut.Obj)
  clear_has_obj();
  return obj_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuYeJiYuCeOutPut::set_allocated_obj(::std::string* obj) {
  if (obj != NULL) {
    set_has_obj();
  } else {
    clear_has_obj();
  }
  obj_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), obj);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuYeJiYuCeOutPut.Obj)
}

// repeated .dzhyun.GeGuYeJiYuCeData data = 2;
inline int GeGuYeJiYuCeOutPut::data_size() const {
  return data_.size();
}
inline void GeGuYeJiYuCeOutPut::clear_data() {
  data_.Clear();
}
inline const ::dzhyun::GeGuYeJiYuCeData& GeGuYeJiYuCeOutPut::data(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuYeJiYuCeOutPut.data)
  return data_.Get(index);
}
inline ::dzhyun::GeGuYeJiYuCeData* GeGuYeJiYuCeOutPut::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuYeJiYuCeOutPut.data)
  return data_.Mutable(index);
}
inline ::dzhyun::GeGuYeJiYuCeData* GeGuYeJiYuCeOutPut::add_data() {
  // @@protoc_insertion_point(field_add:dzhyun.GeGuYeJiYuCeOutPut.data)
  return data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCeData >*
GeGuYeJiYuCeOutPut::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.GeGuYeJiYuCeOutPut.data)
  return &data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuYeJiYuCeData >&
GeGuYeJiYuCeOutPut::data() const {
  // @@protoc_insertion_point(field_list:dzhyun.GeGuYeJiYuCeOutPut.data)
  return data_;
}

// -------------------------------------------------------------------

// GeGuTouZiYanBao

// required string baoGaoRiQi = 1;
inline bool GeGuTouZiYanBao::has_baogaoriqi() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GeGuTouZiYanBao::set_has_baogaoriqi() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GeGuTouZiYanBao::clear_has_baogaoriqi() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GeGuTouZiYanBao::clear_baogaoriqi() {
  baogaoriqi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_baogaoriqi();
}
inline const ::std::string& GeGuTouZiYanBao::baogaoriqi() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBao.baoGaoRiQi)
  return baogaoriqi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_baogaoriqi(const ::std::string& value) {
  set_has_baogaoriqi();
  baogaoriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuTouZiYanBao.baoGaoRiQi)
}
inline void GeGuTouZiYanBao::set_baogaoriqi(const char* value) {
  set_has_baogaoriqi();
  baogaoriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuTouZiYanBao.baoGaoRiQi)
}
inline void GeGuTouZiYanBao::set_baogaoriqi(const char* value, size_t size) {
  set_has_baogaoriqi();
  baogaoriqi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuTouZiYanBao.baoGaoRiQi)
}
inline ::std::string* GeGuTouZiYanBao::mutable_baogaoriqi() {
  set_has_baogaoriqi();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBao.baoGaoRiQi)
  return baogaoriqi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuTouZiYanBao::release_baogaoriqi() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuTouZiYanBao.baoGaoRiQi)
  clear_has_baogaoriqi();
  return baogaoriqi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_allocated_baogaoriqi(::std::string* baogaoriqi) {
  if (baogaoriqi != NULL) {
    set_has_baogaoriqi();
  } else {
    clear_has_baogaoriqi();
  }
  baogaoriqi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), baogaoriqi);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuTouZiYanBao.baoGaoRiQi)
}

// optional string yanJiuJiGou = 2;
inline bool GeGuTouZiYanBao::has_yanjiujigou() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GeGuTouZiYanBao::set_has_yanjiujigou() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GeGuTouZiYanBao::clear_has_yanjiujigou() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GeGuTouZiYanBao::clear_yanjiujigou() {
  yanjiujigou_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_yanjiujigou();
}
inline const ::std::string& GeGuTouZiYanBao::yanjiujigou() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBao.yanJiuJiGou)
  return yanjiujigou_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_yanjiujigou(const ::std::string& value) {
  set_has_yanjiujigou();
  yanjiujigou_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuTouZiYanBao.yanJiuJiGou)
}
inline void GeGuTouZiYanBao::set_yanjiujigou(const char* value) {
  set_has_yanjiujigou();
  yanjiujigou_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuTouZiYanBao.yanJiuJiGou)
}
inline void GeGuTouZiYanBao::set_yanjiujigou(const char* value, size_t size) {
  set_has_yanjiujigou();
  yanjiujigou_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuTouZiYanBao.yanJiuJiGou)
}
inline ::std::string* GeGuTouZiYanBao::mutable_yanjiujigou() {
  set_has_yanjiujigou();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBao.yanJiuJiGou)
  return yanjiujigou_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuTouZiYanBao::release_yanjiujigou() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuTouZiYanBao.yanJiuJiGou)
  clear_has_yanjiujigou();
  return yanjiujigou_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_allocated_yanjiujigou(::std::string* yanjiujigou) {
  if (yanjiujigou != NULL) {
    set_has_yanjiujigou();
  } else {
    clear_has_yanjiujigou();
  }
  yanjiujigou_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), yanjiujigou);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuTouZiYanBao.yanJiuJiGou)
}

// optional string pinJiLeiBie = 3;
inline bool GeGuTouZiYanBao::has_pinjileibie() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GeGuTouZiYanBao::set_has_pinjileibie() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GeGuTouZiYanBao::clear_has_pinjileibie() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GeGuTouZiYanBao::clear_pinjileibie() {
  pinjileibie_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_pinjileibie();
}
inline const ::std::string& GeGuTouZiYanBao::pinjileibie() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBao.pinJiLeiBie)
  return pinjileibie_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_pinjileibie(const ::std::string& value) {
  set_has_pinjileibie();
  pinjileibie_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuTouZiYanBao.pinJiLeiBie)
}
inline void GeGuTouZiYanBao::set_pinjileibie(const char* value) {
  set_has_pinjileibie();
  pinjileibie_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuTouZiYanBao.pinJiLeiBie)
}
inline void GeGuTouZiYanBao::set_pinjileibie(const char* value, size_t size) {
  set_has_pinjileibie();
  pinjileibie_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuTouZiYanBao.pinJiLeiBie)
}
inline ::std::string* GeGuTouZiYanBao::mutable_pinjileibie() {
  set_has_pinjileibie();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBao.pinJiLeiBie)
  return pinjileibie_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuTouZiYanBao::release_pinjileibie() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuTouZiYanBao.pinJiLeiBie)
  clear_has_pinjileibie();
  return pinjileibie_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_allocated_pinjileibie(::std::string* pinjileibie) {
  if (pinjileibie != NULL) {
    set_has_pinjileibie();
  } else {
    clear_has_pinjileibie();
  }
  pinjileibie_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pinjileibie);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuTouZiYanBao.pinJiLeiBie)
}

// optional string pinJiBianDong = 4;
inline bool GeGuTouZiYanBao::has_pinjibiandong() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GeGuTouZiYanBao::set_has_pinjibiandong() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GeGuTouZiYanBao::clear_has_pinjibiandong() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GeGuTouZiYanBao::clear_pinjibiandong() {
  pinjibiandong_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_pinjibiandong();
}
inline const ::std::string& GeGuTouZiYanBao::pinjibiandong() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBao.pinJiBianDong)
  return pinjibiandong_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_pinjibiandong(const ::std::string& value) {
  set_has_pinjibiandong();
  pinjibiandong_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuTouZiYanBao.pinJiBianDong)
}
inline void GeGuTouZiYanBao::set_pinjibiandong(const char* value) {
  set_has_pinjibiandong();
  pinjibiandong_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuTouZiYanBao.pinJiBianDong)
}
inline void GeGuTouZiYanBao::set_pinjibiandong(const char* value, size_t size) {
  set_has_pinjibiandong();
  pinjibiandong_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuTouZiYanBao.pinJiBianDong)
}
inline ::std::string* GeGuTouZiYanBao::mutable_pinjibiandong() {
  set_has_pinjibiandong();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBao.pinJiBianDong)
  return pinjibiandong_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuTouZiYanBao::release_pinjibiandong() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuTouZiYanBao.pinJiBianDong)
  clear_has_pinjibiandong();
  return pinjibiandong_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_allocated_pinjibiandong(::std::string* pinjibiandong) {
  if (pinjibiandong != NULL) {
    set_has_pinjibiandong();
  } else {
    clear_has_pinjibiandong();
  }
  pinjibiandong_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pinjibiandong);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuTouZiYanBao.pinJiBianDong)
}

// optional string yanBaoBiaoTi = 5;
inline bool GeGuTouZiYanBao::has_yanbaobiaoti() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GeGuTouZiYanBao::set_has_yanbaobiaoti() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GeGuTouZiYanBao::clear_has_yanbaobiaoti() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GeGuTouZiYanBao::clear_yanbaobiaoti() {
  yanbaobiaoti_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_yanbaobiaoti();
}
inline const ::std::string& GeGuTouZiYanBao::yanbaobiaoti() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBao.yanBaoBiaoTi)
  return yanbaobiaoti_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_yanbaobiaoti(const ::std::string& value) {
  set_has_yanbaobiaoti();
  yanbaobiaoti_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuTouZiYanBao.yanBaoBiaoTi)
}
inline void GeGuTouZiYanBao::set_yanbaobiaoti(const char* value) {
  set_has_yanbaobiaoti();
  yanbaobiaoti_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuTouZiYanBao.yanBaoBiaoTi)
}
inline void GeGuTouZiYanBao::set_yanbaobiaoti(const char* value, size_t size) {
  set_has_yanbaobiaoti();
  yanbaobiaoti_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuTouZiYanBao.yanBaoBiaoTi)
}
inline ::std::string* GeGuTouZiYanBao::mutable_yanbaobiaoti() {
  set_has_yanbaobiaoti();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBao.yanBaoBiaoTi)
  return yanbaobiaoti_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuTouZiYanBao::release_yanbaobiaoti() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuTouZiYanBao.yanBaoBiaoTi)
  clear_has_yanbaobiaoti();
  return yanbaobiaoti_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_allocated_yanbaobiaoti(::std::string* yanbaobiaoti) {
  if (yanbaobiaoti != NULL) {
    set_has_yanbaobiaoti();
  } else {
    clear_has_yanbaobiaoti();
  }
  yanbaobiaoti_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), yanbaobiaoti);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuTouZiYanBao.yanBaoBiaoTi)
}

// optional string yanBaoNeiRong = 6;
inline bool GeGuTouZiYanBao::has_yanbaoneirong() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void GeGuTouZiYanBao::set_has_yanbaoneirong() {
  _has_bits_[0] |= 0x00000020u;
}
inline void GeGuTouZiYanBao::clear_has_yanbaoneirong() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void GeGuTouZiYanBao::clear_yanbaoneirong() {
  yanbaoneirong_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_yanbaoneirong();
}
inline const ::std::string& GeGuTouZiYanBao::yanbaoneirong() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBao.yanBaoNeiRong)
  return yanbaoneirong_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_yanbaoneirong(const ::std::string& value) {
  set_has_yanbaoneirong();
  yanbaoneirong_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuTouZiYanBao.yanBaoNeiRong)
}
inline void GeGuTouZiYanBao::set_yanbaoneirong(const char* value) {
  set_has_yanbaoneirong();
  yanbaoneirong_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuTouZiYanBao.yanBaoNeiRong)
}
inline void GeGuTouZiYanBao::set_yanbaoneirong(const char* value, size_t size) {
  set_has_yanbaoneirong();
  yanbaoneirong_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuTouZiYanBao.yanBaoNeiRong)
}
inline ::std::string* GeGuTouZiYanBao::mutable_yanbaoneirong() {
  set_has_yanbaoneirong();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBao.yanBaoNeiRong)
  return yanbaoneirong_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuTouZiYanBao::release_yanbaoneirong() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuTouZiYanBao.yanBaoNeiRong)
  clear_has_yanbaoneirong();
  return yanbaoneirong_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_allocated_yanbaoneirong(::std::string* yanbaoneirong) {
  if (yanbaoneirong != NULL) {
    set_has_yanbaoneirong();
  } else {
    clear_has_yanbaoneirong();
  }
  yanbaoneirong_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), yanbaoneirong);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuTouZiYanBao.yanBaoNeiRong)
}

// optional string yanJiuZuoZhe = 7;
inline bool GeGuTouZiYanBao::has_yanjiuzuozhe() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void GeGuTouZiYanBao::set_has_yanjiuzuozhe() {
  _has_bits_[0] |= 0x00000040u;
}
inline void GeGuTouZiYanBao::clear_has_yanjiuzuozhe() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void GeGuTouZiYanBao::clear_yanjiuzuozhe() {
  yanjiuzuozhe_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_yanjiuzuozhe();
}
inline const ::std::string& GeGuTouZiYanBao::yanjiuzuozhe() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBao.yanJiuZuoZhe)
  return yanjiuzuozhe_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_yanjiuzuozhe(const ::std::string& value) {
  set_has_yanjiuzuozhe();
  yanjiuzuozhe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuTouZiYanBao.yanJiuZuoZhe)
}
inline void GeGuTouZiYanBao::set_yanjiuzuozhe(const char* value) {
  set_has_yanjiuzuozhe();
  yanjiuzuozhe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuTouZiYanBao.yanJiuZuoZhe)
}
inline void GeGuTouZiYanBao::set_yanjiuzuozhe(const char* value, size_t size) {
  set_has_yanjiuzuozhe();
  yanjiuzuozhe_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuTouZiYanBao.yanJiuZuoZhe)
}
inline ::std::string* GeGuTouZiYanBao::mutable_yanjiuzuozhe() {
  set_has_yanjiuzuozhe();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBao.yanJiuZuoZhe)
  return yanjiuzuozhe_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuTouZiYanBao::release_yanjiuzuozhe() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuTouZiYanBao.yanJiuZuoZhe)
  clear_has_yanjiuzuozhe();
  return yanjiuzuozhe_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_allocated_yanjiuzuozhe(::std::string* yanjiuzuozhe) {
  if (yanjiuzuozhe != NULL) {
    set_has_yanjiuzuozhe();
  } else {
    clear_has_yanjiuzuozhe();
  }
  yanjiuzuozhe_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), yanjiuzuozhe);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuTouZiYanBao.yanJiuZuoZhe)
}

// optional string muBiaoJiaGe = 8;
inline bool GeGuTouZiYanBao::has_mubiaojiage() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void GeGuTouZiYanBao::set_has_mubiaojiage() {
  _has_bits_[0] |= 0x00000080u;
}
inline void GeGuTouZiYanBao::clear_has_mubiaojiage() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void GeGuTouZiYanBao::clear_mubiaojiage() {
  mubiaojiage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_mubiaojiage();
}
inline const ::std::string& GeGuTouZiYanBao::mubiaojiage() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBao.muBiaoJiaGe)
  return mubiaojiage_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_mubiaojiage(const ::std::string& value) {
  set_has_mubiaojiage();
  mubiaojiage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuTouZiYanBao.muBiaoJiaGe)
}
inline void GeGuTouZiYanBao::set_mubiaojiage(const char* value) {
  set_has_mubiaojiage();
  mubiaojiage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuTouZiYanBao.muBiaoJiaGe)
}
inline void GeGuTouZiYanBao::set_mubiaojiage(const char* value, size_t size) {
  set_has_mubiaojiage();
  mubiaojiage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuTouZiYanBao.muBiaoJiaGe)
}
inline ::std::string* GeGuTouZiYanBao::mutable_mubiaojiage() {
  set_has_mubiaojiage();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBao.muBiaoJiaGe)
  return mubiaojiage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuTouZiYanBao::release_mubiaojiage() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuTouZiYanBao.muBiaoJiaGe)
  clear_has_mubiaojiage();
  return mubiaojiage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBao::set_allocated_mubiaojiage(::std::string* mubiaojiage) {
  if (mubiaojiage != NULL) {
    set_has_mubiaojiage();
  } else {
    clear_has_mubiaojiage();
  }
  mubiaojiage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mubiaojiage);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuTouZiYanBao.muBiaoJiaGe)
}

// -------------------------------------------------------------------

// GeGuTouZiYanBaoOutPut

// required string Obj = 1;
inline bool GeGuTouZiYanBaoOutPut::has_obj() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GeGuTouZiYanBaoOutPut::set_has_obj() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GeGuTouZiYanBaoOutPut::clear_has_obj() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GeGuTouZiYanBaoOutPut::clear_obj() {
  obj_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_obj();
}
inline const ::std::string& GeGuTouZiYanBaoOutPut::obj() const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBaoOutPut.Obj)
  return obj_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBaoOutPut::set_obj(const ::std::string& value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.GeGuTouZiYanBaoOutPut.Obj)
}
inline void GeGuTouZiYanBaoOutPut::set_obj(const char* value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.GeGuTouZiYanBaoOutPut.Obj)
}
inline void GeGuTouZiYanBaoOutPut::set_obj(const char* value, size_t size) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.GeGuTouZiYanBaoOutPut.Obj)
}
inline ::std::string* GeGuTouZiYanBaoOutPut::mutable_obj() {
  set_has_obj();
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBaoOutPut.Obj)
  return obj_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GeGuTouZiYanBaoOutPut::release_obj() {
  // @@protoc_insertion_point(field_release:dzhyun.GeGuTouZiYanBaoOutPut.Obj)
  clear_has_obj();
  return obj_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GeGuTouZiYanBaoOutPut::set_allocated_obj(::std::string* obj) {
  if (obj != NULL) {
    set_has_obj();
  } else {
    clear_has_obj();
  }
  obj_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), obj);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.GeGuTouZiYanBaoOutPut.Obj)
}

// repeated .dzhyun.GeGuTouZiYanBao Data = 2;
inline int GeGuTouZiYanBaoOutPut::data_size() const {
  return data_.size();
}
inline void GeGuTouZiYanBaoOutPut::clear_data() {
  data_.Clear();
}
inline const ::dzhyun::GeGuTouZiYanBao& GeGuTouZiYanBaoOutPut::data(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.GeGuTouZiYanBaoOutPut.Data)
  return data_.Get(index);
}
inline ::dzhyun::GeGuTouZiYanBao* GeGuTouZiYanBaoOutPut::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.GeGuTouZiYanBaoOutPut.Data)
  return data_.Mutable(index);
}
inline ::dzhyun::GeGuTouZiYanBao* GeGuTouZiYanBaoOutPut::add_data() {
  // @@protoc_insertion_point(field_add:dzhyun.GeGuTouZiYanBaoOutPut.Data)
  return data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuTouZiYanBao >*
GeGuTouZiYanBaoOutPut::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.GeGuTouZiYanBaoOutPut.Data)
  return &data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::dzhyun::GeGuTouZiYanBao >&
GeGuTouZiYanBaoOutPut::data() const {
  // @@protoc_insertion_point(field_list:dzhyun.GeGuTouZiYanBaoOutPut.Data)
  return data_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dzhyun

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CldForecastsShuJu_2eproto__INCLUDED
