// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.hkdyna.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dzhyun.hkdyna.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace dzhyun {

namespace {

const ::google::protobuf::Descriptor* HKDynaInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HKDynaInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* HKDynaInfo_HKBroker_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HKDynaInfo_HKBroker_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_dzhyun_2ehkdyna_2eproto() {
  protobuf_AddDesc_dzhyun_2ehkdyna_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "dzhyun.hkdyna.proto");
  GOOGLE_CHECK(file != NULL);
  HKDynaInfo_descriptor_ = file->message_type(0);
  static const int HKDynaInfo_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo, obj_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo, shijian_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo, mairujingjiduilie_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo, maichujingjiduilie_),
  };
  HKDynaInfo_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      HKDynaInfo_descriptor_,
      HKDynaInfo::default_instance_,
      HKDynaInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo, _has_bits_[0]),
      -1,
      -1,
      sizeof(HKDynaInfo),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo, _internal_metadata_),
      -1);
  HKDynaInfo_HKBroker_descriptor_ = HKDynaInfo_descriptor_->nested_type(0);
  static const int HKDynaInfo_HKBroker_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo_HKBroker, duiliehao_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo_HKBroker, leixing_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo_HKBroker, jiage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo_HKBroker, liang_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo_HKBroker, duilieshuju_),
  };
  HKDynaInfo_HKBroker_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      HKDynaInfo_HKBroker_descriptor_,
      HKDynaInfo_HKBroker::default_instance_,
      HKDynaInfo_HKBroker_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo_HKBroker, _has_bits_[0]),
      -1,
      -1,
      sizeof(HKDynaInfo_HKBroker),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HKDynaInfo_HKBroker, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_dzhyun_2ehkdyna_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      HKDynaInfo_descriptor_, &HKDynaInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      HKDynaInfo_HKBroker_descriptor_, &HKDynaInfo_HKBroker::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_dzhyun_2ehkdyna_2eproto() {
  delete HKDynaInfo::default_instance_;
  delete HKDynaInfo_reflection_;
  delete HKDynaInfo_HKBroker::default_instance_;
  delete HKDynaInfo_HKBroker_reflection_;
}

void protobuf_AddDesc_dzhyun_2ehkdyna_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023dzhyun.hkdyna.proto\022\006dzhyun\"\376\001\n\nHKDyna"
    "Info\022\013\n\003Obj\030\001 \002(\t\022\017\n\007ShiJian\030\002 \001(\003\0226\n\021Ma"
    "iRuJingJiDuiLie\030\003 \003(\0132\033.dzhyun.HKDynaInf"
    "o.HKBroker\0227\n\022MaiChuJingJiDuiLie\030\004 \003(\0132\033"
    ".dzhyun.HKDynaInfo.HKBroker\032a\n\010HKBroker\022"
    "\021\n\tDuiLieHao\030\001 \001(\003\022\017\n\007LeiXing\030\002 \001(\t\022\r\n\005J"
    "iaGe\030\003 \001(\003\022\r\n\005Liang\030\004 \001(\003\022\023\n\013DuiLieShuJu"
    "\030\005 \003(\003B\022\n\020com.dzhyun.proto", 306);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dzhyun.hkdyna.proto", &protobuf_RegisterTypes);
  HKDynaInfo::default_instance_ = new HKDynaInfo();
  HKDynaInfo_HKBroker::default_instance_ = new HKDynaInfo_HKBroker();
  HKDynaInfo::default_instance_->InitAsDefaultInstance();
  HKDynaInfo_HKBroker::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_dzhyun_2ehkdyna_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_dzhyun_2ehkdyna_2eproto {
  StaticDescriptorInitializer_dzhyun_2ehkdyna_2eproto() {
    protobuf_AddDesc_dzhyun_2ehkdyna_2eproto();
  }
} static_descriptor_initializer_dzhyun_2ehkdyna_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HKDynaInfo_HKBroker::kDuiLieHaoFieldNumber;
const int HKDynaInfo_HKBroker::kLeiXingFieldNumber;
const int HKDynaInfo_HKBroker::kJiaGeFieldNumber;
const int HKDynaInfo_HKBroker::kLiangFieldNumber;
const int HKDynaInfo_HKBroker::kDuiLieShuJuFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HKDynaInfo_HKBroker::HKDynaInfo_HKBroker()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dzhyun.HKDynaInfo.HKBroker)
}

void HKDynaInfo_HKBroker::InitAsDefaultInstance() {
}

HKDynaInfo_HKBroker::HKDynaInfo_HKBroker(const HKDynaInfo_HKBroker& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dzhyun.HKDynaInfo.HKBroker)
}

void HKDynaInfo_HKBroker::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  duiliehao_ = GOOGLE_LONGLONG(0);
  leixing_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  jiage_ = GOOGLE_LONGLONG(0);
  liang_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HKDynaInfo_HKBroker::~HKDynaInfo_HKBroker() {
  // @@protoc_insertion_point(destructor:dzhyun.HKDynaInfo.HKBroker)
  SharedDtor();
}

void HKDynaInfo_HKBroker::SharedDtor() {
  leixing_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void HKDynaInfo_HKBroker::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HKDynaInfo_HKBroker::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HKDynaInfo_HKBroker_descriptor_;
}

const HKDynaInfo_HKBroker& HKDynaInfo_HKBroker::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dzhyun_2ehkdyna_2eproto();
  return *default_instance_;
}

HKDynaInfo_HKBroker* HKDynaInfo_HKBroker::default_instance_ = NULL;

HKDynaInfo_HKBroker* HKDynaInfo_HKBroker::New(::google::protobuf::Arena* arena) const {
  HKDynaInfo_HKBroker* n = new HKDynaInfo_HKBroker;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HKDynaInfo_HKBroker::Clear() {
// @@protoc_insertion_point(message_clear_start:dzhyun.HKDynaInfo.HKBroker)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(HKDynaInfo_HKBroker, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<HKDynaInfo_HKBroker*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 15u) {
    ZR_(jiage_, liang_);
    duiliehao_ = GOOGLE_LONGLONG(0);
    if (has_leixing()) {
      leixing_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  duilieshuju_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool HKDynaInfo_HKBroker::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dzhyun.HKDynaInfo.HKBroker)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 DuiLieHao = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &duiliehao_)));
          set_has_duiliehao();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_LeiXing;
        break;
      }

      // optional string LeiXing = 2;
      case 2: {
        if (tag == 18) {
         parse_LeiXing:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_leixing()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->leixing().data(), this->leixing().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "dzhyun.HKDynaInfo.HKBroker.LeiXing");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_JiaGe;
        break;
      }

      // optional int64 JiaGe = 3;
      case 3: {
        if (tag == 24) {
         parse_JiaGe:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &jiage_)));
          set_has_jiage();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_Liang;
        break;
      }

      // optional int64 Liang = 4;
      case 4: {
        if (tag == 32) {
         parse_Liang:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &liang_)));
          set_has_liang();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_DuiLieShuJu;
        break;
      }

      // repeated int64 DuiLieShuJu = 5;
      case 5: {
        if (tag == 40) {
         parse_DuiLieShuJu:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 1, 40, input, this->mutable_duilieshuju())));
        } else if (tag == 42) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, this->mutable_duilieshuju())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_DuiLieShuJu;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dzhyun.HKDynaInfo.HKBroker)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dzhyun.HKDynaInfo.HKBroker)
  return false;
#undef DO_
}

void HKDynaInfo_HKBroker::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dzhyun.HKDynaInfo.HKBroker)
  // optional int64 DuiLieHao = 1;
  if (has_duiliehao()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->duiliehao(), output);
  }

  // optional string LeiXing = 2;
  if (has_leixing()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->leixing().data(), this->leixing().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "dzhyun.HKDynaInfo.HKBroker.LeiXing");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->leixing(), output);
  }

  // optional int64 JiaGe = 3;
  if (has_jiage()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->jiage(), output);
  }

  // optional int64 Liang = 4;
  if (has_liang()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->liang(), output);
  }

  // repeated int64 DuiLieShuJu = 5;
  for (int i = 0; i < this->duilieshuju_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(
      5, this->duilieshuju(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dzhyun.HKDynaInfo.HKBroker)
}

::google::protobuf::uint8* HKDynaInfo_HKBroker::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dzhyun.HKDynaInfo.HKBroker)
  // optional int64 DuiLieHao = 1;
  if (has_duiliehao()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->duiliehao(), target);
  }

  // optional string LeiXing = 2;
  if (has_leixing()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->leixing().data(), this->leixing().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "dzhyun.HKDynaInfo.HKBroker.LeiXing");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->leixing(), target);
  }

  // optional int64 JiaGe = 3;
  if (has_jiage()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->jiage(), target);
  }

  // optional int64 Liang = 4;
  if (has_liang()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->liang(), target);
  }

  // repeated int64 DuiLieShuJu = 5;
  for (int i = 0; i < this->duilieshuju_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt64ToArray(5, this->duilieshuju(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dzhyun.HKDynaInfo.HKBroker)
  return target;
}

int HKDynaInfo_HKBroker::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:dzhyun.HKDynaInfo.HKBroker)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 15u) {
    // optional int64 DuiLieHao = 1;
    if (has_duiliehao()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->duiliehao());
    }

    // optional string LeiXing = 2;
    if (has_leixing()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->leixing());
    }

    // optional int64 JiaGe = 3;
    if (has_jiage()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->jiage());
    }

    // optional int64 Liang = 4;
    if (has_liang()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->liang());
    }

  }
  // repeated int64 DuiLieShuJu = 5;
  {
    int data_size = 0;
    for (int i = 0; i < this->duilieshuju_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int64Size(this->duilieshuju(i));
    }
    total_size += 1 * this->duilieshuju_size() + data_size;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HKDynaInfo_HKBroker::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dzhyun.HKDynaInfo.HKBroker)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const HKDynaInfo_HKBroker* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const HKDynaInfo_HKBroker>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dzhyun.HKDynaInfo.HKBroker)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dzhyun.HKDynaInfo.HKBroker)
    MergeFrom(*source);
  }
}

void HKDynaInfo_HKBroker::MergeFrom(const HKDynaInfo_HKBroker& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dzhyun.HKDynaInfo.HKBroker)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  duilieshuju_.MergeFrom(from.duilieshuju_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_duiliehao()) {
      set_duiliehao(from.duiliehao());
    }
    if (from.has_leixing()) {
      set_has_leixing();
      leixing_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.leixing_);
    }
    if (from.has_jiage()) {
      set_jiage(from.jiage());
    }
    if (from.has_liang()) {
      set_liang(from.liang());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void HKDynaInfo_HKBroker::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dzhyun.HKDynaInfo.HKBroker)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HKDynaInfo_HKBroker::CopyFrom(const HKDynaInfo_HKBroker& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dzhyun.HKDynaInfo.HKBroker)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HKDynaInfo_HKBroker::IsInitialized() const {

  return true;
}

void HKDynaInfo_HKBroker::Swap(HKDynaInfo_HKBroker* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HKDynaInfo_HKBroker::InternalSwap(HKDynaInfo_HKBroker* other) {
  std::swap(duiliehao_, other->duiliehao_);
  leixing_.Swap(&other->leixing_);
  std::swap(jiage_, other->jiage_);
  std::swap(liang_, other->liang_);
  duilieshuju_.UnsafeArenaSwap(&other->duilieshuju_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HKDynaInfo_HKBroker::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HKDynaInfo_HKBroker_descriptor_;
  metadata.reflection = HKDynaInfo_HKBroker_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HKDynaInfo::kObjFieldNumber;
const int HKDynaInfo::kShiJianFieldNumber;
const int HKDynaInfo::kMaiRuJingJiDuiLieFieldNumber;
const int HKDynaInfo::kMaiChuJingJiDuiLieFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HKDynaInfo::HKDynaInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dzhyun.HKDynaInfo)
}

void HKDynaInfo::InitAsDefaultInstance() {
}

HKDynaInfo::HKDynaInfo(const HKDynaInfo& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dzhyun.HKDynaInfo)
}

void HKDynaInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  obj_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  shijian_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HKDynaInfo::~HKDynaInfo() {
  // @@protoc_insertion_point(destructor:dzhyun.HKDynaInfo)
  SharedDtor();
}

void HKDynaInfo::SharedDtor() {
  obj_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void HKDynaInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HKDynaInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HKDynaInfo_descriptor_;
}

const HKDynaInfo& HKDynaInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dzhyun_2ehkdyna_2eproto();
  return *default_instance_;
}

HKDynaInfo* HKDynaInfo::default_instance_ = NULL;

HKDynaInfo* HKDynaInfo::New(::google::protobuf::Arena* arena) const {
  HKDynaInfo* n = new HKDynaInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HKDynaInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:dzhyun.HKDynaInfo)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_obj()) {
      obj_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    shijian_ = GOOGLE_LONGLONG(0);
  }
  mairujingjiduilie_.Clear();
  maichujingjiduilie_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool HKDynaInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dzhyun.HKDynaInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string Obj = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_obj()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->obj().data(), this->obj().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "dzhyun.HKDynaInfo.Obj");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_ShiJian;
        break;
      }

      // optional int64 ShiJian = 2;
      case 2: {
        if (tag == 16) {
         parse_ShiJian:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &shijian_)));
          set_has_shijian();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_MaiRuJingJiDuiLie;
        break;
      }

      // repeated .dzhyun.HKDynaInfo.HKBroker MaiRuJingJiDuiLie = 3;
      case 3: {
        if (tag == 26) {
         parse_MaiRuJingJiDuiLie:
          DO_(input->IncrementRecursionDepth());
         parse_loop_MaiRuJingJiDuiLie:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_mairujingjiduilie()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_MaiRuJingJiDuiLie;
        if (input->ExpectTag(34)) goto parse_loop_MaiChuJingJiDuiLie;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .dzhyun.HKDynaInfo.HKBroker MaiChuJingJiDuiLie = 4;
      case 4: {
        if (tag == 34) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_MaiChuJingJiDuiLie:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_maichujingjiduilie()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_loop_MaiChuJingJiDuiLie;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dzhyun.HKDynaInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dzhyun.HKDynaInfo)
  return false;
#undef DO_
}

void HKDynaInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dzhyun.HKDynaInfo)
  // required string Obj = 1;
  if (has_obj()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->obj().data(), this->obj().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "dzhyun.HKDynaInfo.Obj");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->obj(), output);
  }

  // optional int64 ShiJian = 2;
  if (has_shijian()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->shijian(), output);
  }

  // repeated .dzhyun.HKDynaInfo.HKBroker MaiRuJingJiDuiLie = 3;
  for (unsigned int i = 0, n = this->mairujingjiduilie_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->mairujingjiduilie(i), output);
  }

  // repeated .dzhyun.HKDynaInfo.HKBroker MaiChuJingJiDuiLie = 4;
  for (unsigned int i = 0, n = this->maichujingjiduilie_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->maichujingjiduilie(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dzhyun.HKDynaInfo)
}

::google::protobuf::uint8* HKDynaInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dzhyun.HKDynaInfo)
  // required string Obj = 1;
  if (has_obj()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->obj().data(), this->obj().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "dzhyun.HKDynaInfo.Obj");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->obj(), target);
  }

  // optional int64 ShiJian = 2;
  if (has_shijian()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->shijian(), target);
  }

  // repeated .dzhyun.HKDynaInfo.HKBroker MaiRuJingJiDuiLie = 3;
  for (unsigned int i = 0, n = this->mairujingjiduilie_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->mairujingjiduilie(i), target);
  }

  // repeated .dzhyun.HKDynaInfo.HKBroker MaiChuJingJiDuiLie = 4;
  for (unsigned int i = 0, n = this->maichujingjiduilie_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->maichujingjiduilie(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dzhyun.HKDynaInfo)
  return target;
}

int HKDynaInfo::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:dzhyun.HKDynaInfo)
  int total_size = 0;

  // required string Obj = 1;
  if (has_obj()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->obj());
  }
  // optional int64 ShiJian = 2;
  if (has_shijian()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->shijian());
  }

  // repeated .dzhyun.HKDynaInfo.HKBroker MaiRuJingJiDuiLie = 3;
  total_size += 1 * this->mairujingjiduilie_size();
  for (int i = 0; i < this->mairujingjiduilie_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->mairujingjiduilie(i));
  }

  // repeated .dzhyun.HKDynaInfo.HKBroker MaiChuJingJiDuiLie = 4;
  total_size += 1 * this->maichujingjiduilie_size();
  for (int i = 0; i < this->maichujingjiduilie_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->maichujingjiduilie(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HKDynaInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dzhyun.HKDynaInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const HKDynaInfo* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const HKDynaInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dzhyun.HKDynaInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dzhyun.HKDynaInfo)
    MergeFrom(*source);
  }
}

void HKDynaInfo::MergeFrom(const HKDynaInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dzhyun.HKDynaInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  mairujingjiduilie_.MergeFrom(from.mairujingjiduilie_);
  maichujingjiduilie_.MergeFrom(from.maichujingjiduilie_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_obj()) {
      set_has_obj();
      obj_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.obj_);
    }
    if (from.has_shijian()) {
      set_shijian(from.shijian());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void HKDynaInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dzhyun.HKDynaInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HKDynaInfo::CopyFrom(const HKDynaInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dzhyun.HKDynaInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HKDynaInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void HKDynaInfo::Swap(HKDynaInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HKDynaInfo::InternalSwap(HKDynaInfo* other) {
  obj_.Swap(&other->obj_);
  std::swap(shijian_, other->shijian_);
  mairujingjiduilie_.UnsafeArenaSwap(&other->mairujingjiduilie_);
  maichujingjiduilie_.UnsafeArenaSwap(&other->maichujingjiduilie_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HKDynaInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HKDynaInfo_descriptor_;
  metadata.reflection = HKDynaInfo_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// HKDynaInfo_HKBroker

// optional int64 DuiLieHao = 1;
bool HKDynaInfo_HKBroker::has_duiliehao() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void HKDynaInfo_HKBroker::set_has_duiliehao() {
  _has_bits_[0] |= 0x00000001u;
}
void HKDynaInfo_HKBroker::clear_has_duiliehao() {
  _has_bits_[0] &= ~0x00000001u;
}
void HKDynaInfo_HKBroker::clear_duiliehao() {
  duiliehao_ = GOOGLE_LONGLONG(0);
  clear_has_duiliehao();
}
 ::google::protobuf::int64 HKDynaInfo_HKBroker::duiliehao() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.DuiLieHao)
  return duiliehao_;
}
 void HKDynaInfo_HKBroker::set_duiliehao(::google::protobuf::int64 value) {
  set_has_duiliehao();
  duiliehao_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.DuiLieHao)
}

// optional string LeiXing = 2;
bool HKDynaInfo_HKBroker::has_leixing() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void HKDynaInfo_HKBroker::set_has_leixing() {
  _has_bits_[0] |= 0x00000002u;
}
void HKDynaInfo_HKBroker::clear_has_leixing() {
  _has_bits_[0] &= ~0x00000002u;
}
void HKDynaInfo_HKBroker::clear_leixing() {
  leixing_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_leixing();
}
 const ::std::string& HKDynaInfo_HKBroker::leixing() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.LeiXing)
  return leixing_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HKDynaInfo_HKBroker::set_leixing(const ::std::string& value) {
  set_has_leixing();
  leixing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.LeiXing)
}
 void HKDynaInfo_HKBroker::set_leixing(const char* value) {
  set_has_leixing();
  leixing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.HKDynaInfo.HKBroker.LeiXing)
}
 void HKDynaInfo_HKBroker::set_leixing(const char* value, size_t size) {
  set_has_leixing();
  leixing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.HKDynaInfo.HKBroker.LeiXing)
}
 ::std::string* HKDynaInfo_HKBroker::mutable_leixing() {
  set_has_leixing();
  // @@protoc_insertion_point(field_mutable:dzhyun.HKDynaInfo.HKBroker.LeiXing)
  return leixing_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HKDynaInfo_HKBroker::release_leixing() {
  // @@protoc_insertion_point(field_release:dzhyun.HKDynaInfo.HKBroker.LeiXing)
  clear_has_leixing();
  return leixing_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HKDynaInfo_HKBroker::set_allocated_leixing(::std::string* leixing) {
  if (leixing != NULL) {
    set_has_leixing();
  } else {
    clear_has_leixing();
  }
  leixing_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), leixing);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.HKDynaInfo.HKBroker.LeiXing)
}

// optional int64 JiaGe = 3;
bool HKDynaInfo_HKBroker::has_jiage() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void HKDynaInfo_HKBroker::set_has_jiage() {
  _has_bits_[0] |= 0x00000004u;
}
void HKDynaInfo_HKBroker::clear_has_jiage() {
  _has_bits_[0] &= ~0x00000004u;
}
void HKDynaInfo_HKBroker::clear_jiage() {
  jiage_ = GOOGLE_LONGLONG(0);
  clear_has_jiage();
}
 ::google::protobuf::int64 HKDynaInfo_HKBroker::jiage() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.JiaGe)
  return jiage_;
}
 void HKDynaInfo_HKBroker::set_jiage(::google::protobuf::int64 value) {
  set_has_jiage();
  jiage_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.JiaGe)
}

// optional int64 Liang = 4;
bool HKDynaInfo_HKBroker::has_liang() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void HKDynaInfo_HKBroker::set_has_liang() {
  _has_bits_[0] |= 0x00000008u;
}
void HKDynaInfo_HKBroker::clear_has_liang() {
  _has_bits_[0] &= ~0x00000008u;
}
void HKDynaInfo_HKBroker::clear_liang() {
  liang_ = GOOGLE_LONGLONG(0);
  clear_has_liang();
}
 ::google::protobuf::int64 HKDynaInfo_HKBroker::liang() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.Liang)
  return liang_;
}
 void HKDynaInfo_HKBroker::set_liang(::google::protobuf::int64 value) {
  set_has_liang();
  liang_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.Liang)
}

// repeated int64 DuiLieShuJu = 5;
int HKDynaInfo_HKBroker::duilieshuju_size() const {
  return duilieshuju_.size();
}
void HKDynaInfo_HKBroker::clear_duilieshuju() {
  duilieshuju_.Clear();
}
 ::google::protobuf::int64 HKDynaInfo_HKBroker::duilieshuju(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
  return duilieshuju_.Get(index);
}
 void HKDynaInfo_HKBroker::set_duilieshuju(int index, ::google::protobuf::int64 value) {
  duilieshuju_.Set(index, value);
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
}
 void HKDynaInfo_HKBroker::add_duilieshuju(::google::protobuf::int64 value) {
  duilieshuju_.Add(value);
  // @@protoc_insertion_point(field_add:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
HKDynaInfo_HKBroker::duilieshuju() const {
  // @@protoc_insertion_point(field_list:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
  return duilieshuju_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
HKDynaInfo_HKBroker::mutable_duilieshuju() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
  return &duilieshuju_;
}

// -------------------------------------------------------------------

// HKDynaInfo

// required string Obj = 1;
bool HKDynaInfo::has_obj() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void HKDynaInfo::set_has_obj() {
  _has_bits_[0] |= 0x00000001u;
}
void HKDynaInfo::clear_has_obj() {
  _has_bits_[0] &= ~0x00000001u;
}
void HKDynaInfo::clear_obj() {
  obj_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_obj();
}
 const ::std::string& HKDynaInfo::obj() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.Obj)
  return obj_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HKDynaInfo::set_obj(const ::std::string& value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.Obj)
}
 void HKDynaInfo::set_obj(const char* value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.HKDynaInfo.Obj)
}
 void HKDynaInfo::set_obj(const char* value, size_t size) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.HKDynaInfo.Obj)
}
 ::std::string* HKDynaInfo::mutable_obj() {
  set_has_obj();
  // @@protoc_insertion_point(field_mutable:dzhyun.HKDynaInfo.Obj)
  return obj_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HKDynaInfo::release_obj() {
  // @@protoc_insertion_point(field_release:dzhyun.HKDynaInfo.Obj)
  clear_has_obj();
  return obj_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HKDynaInfo::set_allocated_obj(::std::string* obj) {
  if (obj != NULL) {
    set_has_obj();
  } else {
    clear_has_obj();
  }
  obj_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), obj);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.HKDynaInfo.Obj)
}

// optional int64 ShiJian = 2;
bool HKDynaInfo::has_shijian() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void HKDynaInfo::set_has_shijian() {
  _has_bits_[0] |= 0x00000002u;
}
void HKDynaInfo::clear_has_shijian() {
  _has_bits_[0] &= ~0x00000002u;
}
void HKDynaInfo::clear_shijian() {
  shijian_ = GOOGLE_LONGLONG(0);
  clear_has_shijian();
}
 ::google::protobuf::int64 HKDynaInfo::shijian() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.ShiJian)
  return shijian_;
}
 void HKDynaInfo::set_shijian(::google::protobuf::int64 value) {
  set_has_shijian();
  shijian_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.ShiJian)
}

// repeated .dzhyun.HKDynaInfo.HKBroker MaiRuJingJiDuiLie = 3;
int HKDynaInfo::mairujingjiduilie_size() const {
  return mairujingjiduilie_.size();
}
void HKDynaInfo::clear_mairujingjiduilie() {
  mairujingjiduilie_.Clear();
}
const ::dzhyun::HKDynaInfo_HKBroker& HKDynaInfo::mairujingjiduilie(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return mairujingjiduilie_.Get(index);
}
::dzhyun::HKDynaInfo_HKBroker* HKDynaInfo::mutable_mairujingjiduilie(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return mairujingjiduilie_.Mutable(index);
}
::dzhyun::HKDynaInfo_HKBroker* HKDynaInfo::add_mairujingjiduilie() {
  // @@protoc_insertion_point(field_add:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return mairujingjiduilie_.Add();
}
::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >*
HKDynaInfo::mutable_mairujingjiduilie() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return &mairujingjiduilie_;
}
const ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >&
HKDynaInfo::mairujingjiduilie() const {
  // @@protoc_insertion_point(field_list:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return mairujingjiduilie_;
}

// repeated .dzhyun.HKDynaInfo.HKBroker MaiChuJingJiDuiLie = 4;
int HKDynaInfo::maichujingjiduilie_size() const {
  return maichujingjiduilie_.size();
}
void HKDynaInfo::clear_maichujingjiduilie() {
  maichujingjiduilie_.Clear();
}
const ::dzhyun::HKDynaInfo_HKBroker& HKDynaInfo::maichujingjiduilie(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return maichujingjiduilie_.Get(index);
}
::dzhyun::HKDynaInfo_HKBroker* HKDynaInfo::mutable_maichujingjiduilie(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return maichujingjiduilie_.Mutable(index);
}
::dzhyun::HKDynaInfo_HKBroker* HKDynaInfo::add_maichujingjiduilie() {
  // @@protoc_insertion_point(field_add:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return maichujingjiduilie_.Add();
}
::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >*
HKDynaInfo::mutable_maichujingjiduilie() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return &maichujingjiduilie_;
}
const ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >&
HKDynaInfo::maichujingjiduilie() const {
  // @@protoc_insertion_point(field_list:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return maichujingjiduilie_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace dzhyun

// @@protoc_insertion_point(global_scope)
