// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.hkdyna.proto

#ifndef PROTOBUF_dzhyun_2ehkdyna_2eproto__INCLUDED
#define PROTOBUF_dzhyun_2ehkdyna_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dzhyun {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_dzhyun_2ehkdyna_2eproto();
void protobuf_AssignDesc_dzhyun_2ehkdyna_2eproto();
void protobuf_ShutdownFile_dzhyun_2ehkdyna_2eproto();

class HKDynaInfo;
class HKDynaInfo_HKBroker;

// ===================================================================

class HKDynaInfo_HKBroker : public ::google::protobuf::Message {
 public:
  HKDynaInfo_HKBroker();
  virtual ~HKDynaInfo_HKBroker();

  HKDynaInfo_HKBroker(const HKDynaInfo_HKBroker& from);

  inline HKDynaInfo_HKBroker& operator=(const HKDynaInfo_HKBroker& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HKDynaInfo_HKBroker& default_instance();

  void Swap(HKDynaInfo_HKBroker* other);

  // implements Message ----------------------------------------------

  inline HKDynaInfo_HKBroker* New() const { return New(NULL); }

  HKDynaInfo_HKBroker* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HKDynaInfo_HKBroker& from);
  void MergeFrom(const HKDynaInfo_HKBroker& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HKDynaInfo_HKBroker* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 DuiLieHao = 1;
  bool has_duiliehao() const;
  void clear_duiliehao();
  static const int kDuiLieHaoFieldNumber = 1;
  ::google::protobuf::int64 duiliehao() const;
  void set_duiliehao(::google::protobuf::int64 value);

  // optional string LeiXing = 2;
  bool has_leixing() const;
  void clear_leixing();
  static const int kLeiXingFieldNumber = 2;
  const ::std::string& leixing() const;
  void set_leixing(const ::std::string& value);
  void set_leixing(const char* value);
  void set_leixing(const char* value, size_t size);
  ::std::string* mutable_leixing();
  ::std::string* release_leixing();
  void set_allocated_leixing(::std::string* leixing);

  // optional int64 JiaGe = 3;
  bool has_jiage() const;
  void clear_jiage();
  static const int kJiaGeFieldNumber = 3;
  ::google::protobuf::int64 jiage() const;
  void set_jiage(::google::protobuf::int64 value);

  // optional int64 Liang = 4;
  bool has_liang() const;
  void clear_liang();
  static const int kLiangFieldNumber = 4;
  ::google::protobuf::int64 liang() const;
  void set_liang(::google::protobuf::int64 value);

  // repeated int64 DuiLieShuJu = 5;
  int duilieshuju_size() const;
  void clear_duilieshuju();
  static const int kDuiLieShuJuFieldNumber = 5;
  ::google::protobuf::int64 duilieshuju(int index) const;
  void set_duilieshuju(int index, ::google::protobuf::int64 value);
  void add_duilieshuju(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      duilieshuju() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_duilieshuju();

  // @@protoc_insertion_point(class_scope:dzhyun.HKDynaInfo.HKBroker)
 private:
  inline void set_has_duiliehao();
  inline void clear_has_duiliehao();
  inline void set_has_leixing();
  inline void clear_has_leixing();
  inline void set_has_jiage();
  inline void clear_has_jiage();
  inline void set_has_liang();
  inline void clear_has_liang();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 duiliehao_;
  ::google::protobuf::internal::ArenaStringPtr leixing_;
  ::google::protobuf::int64 jiage_;
  ::google::protobuf::int64 liang_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > duilieshuju_;
  friend void  protobuf_AddDesc_dzhyun_2ehkdyna_2eproto();
  friend void protobuf_AssignDesc_dzhyun_2ehkdyna_2eproto();
  friend void protobuf_ShutdownFile_dzhyun_2ehkdyna_2eproto();

  void InitAsDefaultInstance();
  static HKDynaInfo_HKBroker* default_instance_;
};
// -------------------------------------------------------------------

class HKDynaInfo : public ::google::protobuf::Message {
 public:
  HKDynaInfo();
  virtual ~HKDynaInfo();

  HKDynaInfo(const HKDynaInfo& from);

  inline HKDynaInfo& operator=(const HKDynaInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HKDynaInfo& default_instance();

  void Swap(HKDynaInfo* other);

  // implements Message ----------------------------------------------

  inline HKDynaInfo* New() const { return New(NULL); }

  HKDynaInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HKDynaInfo& from);
  void MergeFrom(const HKDynaInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HKDynaInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef HKDynaInfo_HKBroker HKBroker;

  // accessors -------------------------------------------------------

  // required string Obj = 1;
  bool has_obj() const;
  void clear_obj();
  static const int kObjFieldNumber = 1;
  const ::std::string& obj() const;
  void set_obj(const ::std::string& value);
  void set_obj(const char* value);
  void set_obj(const char* value, size_t size);
  ::std::string* mutable_obj();
  ::std::string* release_obj();
  void set_allocated_obj(::std::string* obj);

  // optional int64 ShiJian = 2;
  bool has_shijian() const;
  void clear_shijian();
  static const int kShiJianFieldNumber = 2;
  ::google::protobuf::int64 shijian() const;
  void set_shijian(::google::protobuf::int64 value);

  // repeated .dzhyun.HKDynaInfo.HKBroker MaiRuJingJiDuiLie = 3;
  int mairujingjiduilie_size() const;
  void clear_mairujingjiduilie();
  static const int kMaiRuJingJiDuiLieFieldNumber = 3;
  const ::dzhyun::HKDynaInfo_HKBroker& mairujingjiduilie(int index) const;
  ::dzhyun::HKDynaInfo_HKBroker* mutable_mairujingjiduilie(int index);
  ::dzhyun::HKDynaInfo_HKBroker* add_mairujingjiduilie();
  ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >*
      mutable_mairujingjiduilie();
  const ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >&
      mairujingjiduilie() const;

  // repeated .dzhyun.HKDynaInfo.HKBroker MaiChuJingJiDuiLie = 4;
  int maichujingjiduilie_size() const;
  void clear_maichujingjiduilie();
  static const int kMaiChuJingJiDuiLieFieldNumber = 4;
  const ::dzhyun::HKDynaInfo_HKBroker& maichujingjiduilie(int index) const;
  ::dzhyun::HKDynaInfo_HKBroker* mutable_maichujingjiduilie(int index);
  ::dzhyun::HKDynaInfo_HKBroker* add_maichujingjiduilie();
  ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >*
      mutable_maichujingjiduilie();
  const ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >&
      maichujingjiduilie() const;

  // @@protoc_insertion_point(class_scope:dzhyun.HKDynaInfo)
 private:
  inline void set_has_obj();
  inline void clear_has_obj();
  inline void set_has_shijian();
  inline void clear_has_shijian();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr obj_;
  ::google::protobuf::int64 shijian_;
  ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker > mairujingjiduilie_;
  ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker > maichujingjiduilie_;
  friend void  protobuf_AddDesc_dzhyun_2ehkdyna_2eproto();
  friend void protobuf_AssignDesc_dzhyun_2ehkdyna_2eproto();
  friend void protobuf_ShutdownFile_dzhyun_2ehkdyna_2eproto();

  void InitAsDefaultInstance();
  static HKDynaInfo* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HKDynaInfo_HKBroker

// optional int64 DuiLieHao = 1;
inline bool HKDynaInfo_HKBroker::has_duiliehao() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HKDynaInfo_HKBroker::set_has_duiliehao() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HKDynaInfo_HKBroker::clear_has_duiliehao() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HKDynaInfo_HKBroker::clear_duiliehao() {
  duiliehao_ = GOOGLE_LONGLONG(0);
  clear_has_duiliehao();
}
inline ::google::protobuf::int64 HKDynaInfo_HKBroker::duiliehao() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.DuiLieHao)
  return duiliehao_;
}
inline void HKDynaInfo_HKBroker::set_duiliehao(::google::protobuf::int64 value) {
  set_has_duiliehao();
  duiliehao_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.DuiLieHao)
}

// optional string LeiXing = 2;
inline bool HKDynaInfo_HKBroker::has_leixing() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HKDynaInfo_HKBroker::set_has_leixing() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HKDynaInfo_HKBroker::clear_has_leixing() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HKDynaInfo_HKBroker::clear_leixing() {
  leixing_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_leixing();
}
inline const ::std::string& HKDynaInfo_HKBroker::leixing() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.LeiXing)
  return leixing_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HKDynaInfo_HKBroker::set_leixing(const ::std::string& value) {
  set_has_leixing();
  leixing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.LeiXing)
}
inline void HKDynaInfo_HKBroker::set_leixing(const char* value) {
  set_has_leixing();
  leixing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.HKDynaInfo.HKBroker.LeiXing)
}
inline void HKDynaInfo_HKBroker::set_leixing(const char* value, size_t size) {
  set_has_leixing();
  leixing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.HKDynaInfo.HKBroker.LeiXing)
}
inline ::std::string* HKDynaInfo_HKBroker::mutable_leixing() {
  set_has_leixing();
  // @@protoc_insertion_point(field_mutable:dzhyun.HKDynaInfo.HKBroker.LeiXing)
  return leixing_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HKDynaInfo_HKBroker::release_leixing() {
  // @@protoc_insertion_point(field_release:dzhyun.HKDynaInfo.HKBroker.LeiXing)
  clear_has_leixing();
  return leixing_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HKDynaInfo_HKBroker::set_allocated_leixing(::std::string* leixing) {
  if (leixing != NULL) {
    set_has_leixing();
  } else {
    clear_has_leixing();
  }
  leixing_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), leixing);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.HKDynaInfo.HKBroker.LeiXing)
}

// optional int64 JiaGe = 3;
inline bool HKDynaInfo_HKBroker::has_jiage() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HKDynaInfo_HKBroker::set_has_jiage() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HKDynaInfo_HKBroker::clear_has_jiage() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HKDynaInfo_HKBroker::clear_jiage() {
  jiage_ = GOOGLE_LONGLONG(0);
  clear_has_jiage();
}
inline ::google::protobuf::int64 HKDynaInfo_HKBroker::jiage() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.JiaGe)
  return jiage_;
}
inline void HKDynaInfo_HKBroker::set_jiage(::google::protobuf::int64 value) {
  set_has_jiage();
  jiage_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.JiaGe)
}

// optional int64 Liang = 4;
inline bool HKDynaInfo_HKBroker::has_liang() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void HKDynaInfo_HKBroker::set_has_liang() {
  _has_bits_[0] |= 0x00000008u;
}
inline void HKDynaInfo_HKBroker::clear_has_liang() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void HKDynaInfo_HKBroker::clear_liang() {
  liang_ = GOOGLE_LONGLONG(0);
  clear_has_liang();
}
inline ::google::protobuf::int64 HKDynaInfo_HKBroker::liang() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.Liang)
  return liang_;
}
inline void HKDynaInfo_HKBroker::set_liang(::google::protobuf::int64 value) {
  set_has_liang();
  liang_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.Liang)
}

// repeated int64 DuiLieShuJu = 5;
inline int HKDynaInfo_HKBroker::duilieshuju_size() const {
  return duilieshuju_.size();
}
inline void HKDynaInfo_HKBroker::clear_duilieshuju() {
  duilieshuju_.Clear();
}
inline ::google::protobuf::int64 HKDynaInfo_HKBroker::duilieshuju(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
  return duilieshuju_.Get(index);
}
inline void HKDynaInfo_HKBroker::set_duilieshuju(int index, ::google::protobuf::int64 value) {
  duilieshuju_.Set(index, value);
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
}
inline void HKDynaInfo_HKBroker::add_duilieshuju(::google::protobuf::int64 value) {
  duilieshuju_.Add(value);
  // @@protoc_insertion_point(field_add:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
HKDynaInfo_HKBroker::duilieshuju() const {
  // @@protoc_insertion_point(field_list:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
  return duilieshuju_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
HKDynaInfo_HKBroker::mutable_duilieshuju() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.HKDynaInfo.HKBroker.DuiLieShuJu)
  return &duilieshuju_;
}

// -------------------------------------------------------------------

// HKDynaInfo

// required string Obj = 1;
inline bool HKDynaInfo::has_obj() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HKDynaInfo::set_has_obj() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HKDynaInfo::clear_has_obj() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HKDynaInfo::clear_obj() {
  obj_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_obj();
}
inline const ::std::string& HKDynaInfo::obj() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.Obj)
  return obj_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HKDynaInfo::set_obj(const ::std::string& value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.Obj)
}
inline void HKDynaInfo::set_obj(const char* value) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.HKDynaInfo.Obj)
}
inline void HKDynaInfo::set_obj(const char* value, size_t size) {
  set_has_obj();
  obj_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.HKDynaInfo.Obj)
}
inline ::std::string* HKDynaInfo::mutable_obj() {
  set_has_obj();
  // @@protoc_insertion_point(field_mutable:dzhyun.HKDynaInfo.Obj)
  return obj_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HKDynaInfo::release_obj() {
  // @@protoc_insertion_point(field_release:dzhyun.HKDynaInfo.Obj)
  clear_has_obj();
  return obj_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HKDynaInfo::set_allocated_obj(::std::string* obj) {
  if (obj != NULL) {
    set_has_obj();
  } else {
    clear_has_obj();
  }
  obj_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), obj);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.HKDynaInfo.Obj)
}

// optional int64 ShiJian = 2;
inline bool HKDynaInfo::has_shijian() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HKDynaInfo::set_has_shijian() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HKDynaInfo::clear_has_shijian() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HKDynaInfo::clear_shijian() {
  shijian_ = GOOGLE_LONGLONG(0);
  clear_has_shijian();
}
inline ::google::protobuf::int64 HKDynaInfo::shijian() const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.ShiJian)
  return shijian_;
}
inline void HKDynaInfo::set_shijian(::google::protobuf::int64 value) {
  set_has_shijian();
  shijian_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.HKDynaInfo.ShiJian)
}

// repeated .dzhyun.HKDynaInfo.HKBroker MaiRuJingJiDuiLie = 3;
inline int HKDynaInfo::mairujingjiduilie_size() const {
  return mairujingjiduilie_.size();
}
inline void HKDynaInfo::clear_mairujingjiduilie() {
  mairujingjiduilie_.Clear();
}
inline const ::dzhyun::HKDynaInfo_HKBroker& HKDynaInfo::mairujingjiduilie(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return mairujingjiduilie_.Get(index);
}
inline ::dzhyun::HKDynaInfo_HKBroker* HKDynaInfo::mutable_mairujingjiduilie(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return mairujingjiduilie_.Mutable(index);
}
inline ::dzhyun::HKDynaInfo_HKBroker* HKDynaInfo::add_mairujingjiduilie() {
  // @@protoc_insertion_point(field_add:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return mairujingjiduilie_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >*
HKDynaInfo::mutable_mairujingjiduilie() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return &mairujingjiduilie_;
}
inline const ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >&
HKDynaInfo::mairujingjiduilie() const {
  // @@protoc_insertion_point(field_list:dzhyun.HKDynaInfo.MaiRuJingJiDuiLie)
  return mairujingjiduilie_;
}

// repeated .dzhyun.HKDynaInfo.HKBroker MaiChuJingJiDuiLie = 4;
inline int HKDynaInfo::maichujingjiduilie_size() const {
  return maichujingjiduilie_.size();
}
inline void HKDynaInfo::clear_maichujingjiduilie() {
  maichujingjiduilie_.Clear();
}
inline const ::dzhyun::HKDynaInfo_HKBroker& HKDynaInfo::maichujingjiduilie(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return maichujingjiduilie_.Get(index);
}
inline ::dzhyun::HKDynaInfo_HKBroker* HKDynaInfo::mutable_maichujingjiduilie(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return maichujingjiduilie_.Mutable(index);
}
inline ::dzhyun::HKDynaInfo_HKBroker* HKDynaInfo::add_maichujingjiduilie() {
  // @@protoc_insertion_point(field_add:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return maichujingjiduilie_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >*
HKDynaInfo::mutable_maichujingjiduilie() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return &maichujingjiduilie_;
}
inline const ::google::protobuf::RepeatedPtrField< ::dzhyun::HKDynaInfo_HKBroker >&
HKDynaInfo::maichujingjiduilie() const {
  // @@protoc_insertion_point(field_list:dzhyun.HKDynaInfo.MaiChuJingJiDuiLie)
  return maichujingjiduilie_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dzhyun

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dzhyun_2ehkdyna_2eproto__INCLUDED
