// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.jianpanbao.proto

#ifndef PROTOBUF_dzhyun_2ejianpanbao_2eproto__INCLUDED
#define PROTOBUF_dzhyun_2ejianpanbao_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dzhyun {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_dzhyun_2ejianpanbao_2eproto();
void protobuf_AssignDesc_dzhyun_2ejianpanbao_2eproto();
void protobuf_ShutdownFile_dzhyun_2ejianpanbao_2eproto();

class JPBShuChu;
class JPBShuJu;
class JianPanBaoShuChu;

enum JPBLeiXing {
  TYPE_OBJ = 0,
  TYPE_INDI = 1,
  TYPE_TOPIC = 2,
  TYPE_LHB = 3,
  TYPE_BLKOBJ = 4,
  TYPE_TOPICANALY = 5,
  TYPE_OBJPHONE = 6,
  TYPE_OBJATFUND = 7,
  TYPE_OBJATBLOCK = 8,
  TYPE_HKBROKER = 9
};
bool JPBLeiXing_IsValid(int value);
const JPBLeiXing JPBLeiXing_MIN = TYPE_OBJ;
const JPBLeiXing JPBLeiXing_MAX = TYPE_HKBROKER;
const int JPBLeiXing_ARRAYSIZE = JPBLeiXing_MAX + 1;

const ::google::protobuf::EnumDescriptor* JPBLeiXing_descriptor();
inline const ::std::string& JPBLeiXing_Name(JPBLeiXing value) {
  return ::google::protobuf::internal::NameOfEnum(
    JPBLeiXing_descriptor(), value);
}
inline bool JPBLeiXing_Parse(
    const ::std::string& name, JPBLeiXing* value) {
  return ::google::protobuf::internal::ParseNamedEnum<JPBLeiXing>(
    JPBLeiXing_descriptor(), name, value);
}
// ===================================================================

class JPBShuJu : public ::google::protobuf::Message {
 public:
  JPBShuJu();
  virtual ~JPBShuJu();

  JPBShuJu(const JPBShuJu& from);

  inline JPBShuJu& operator=(const JPBShuJu& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JPBShuJu& default_instance();

  void Swap(JPBShuJu* other);

  // implements Message ----------------------------------------------

  inline JPBShuJu* New() const { return New(NULL); }

  JPBShuJu* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JPBShuJu& from);
  void MergeFrom(const JPBShuJu& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JPBShuJu* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string DaiMa = 1;
  bool has_daima() const;
  void clear_daima();
  static const int kDaiMaFieldNumber = 1;
  const ::std::string& daima() const;
  void set_daima(const ::std::string& value);
  void set_daima(const char* value);
  void set_daima(const char* value, size_t size);
  ::std::string* mutable_daima();
  ::std::string* release_daima();
  void set_allocated_daima(::std::string* daima);

  // required string MingCheng = 2;
  bool has_mingcheng() const;
  void clear_mingcheng();
  static const int kMingChengFieldNumber = 2;
  const ::std::string& mingcheng() const;
  void set_mingcheng(const ::std::string& value);
  void set_mingcheng(const char* value);
  void set_mingcheng(const char* value, size_t size);
  ::std::string* mutable_mingcheng();
  ::std::string* release_mingcheng();
  void set_allocated_mingcheng(::std::string* mingcheng);

  // optional string ShuXing = 3;
  bool has_shuxing() const;
  void clear_shuxing();
  static const int kShuXingFieldNumber = 3;
  const ::std::string& shuxing() const;
  void set_shuxing(const ::std::string& value);
  void set_shuxing(const char* value);
  void set_shuxing(const char* value, size_t size);
  ::std::string* mutable_shuxing();
  ::std::string* release_shuxing();
  void set_allocated_shuxing(::std::string* shuxing);

  // optional string KuoZhan = 4;
  bool has_kuozhan() const;
  void clear_kuozhan();
  static const int kKuoZhanFieldNumber = 4;
  const ::std::string& kuozhan() const;
  void set_kuozhan(const ::std::string& value);
  void set_kuozhan(const char* value);
  void set_kuozhan(const char* value, size_t size);
  ::std::string* mutable_kuozhan();
  ::std::string* release_kuozhan();
  void set_allocated_kuozhan(::std::string* kuozhan);

  // @@protoc_insertion_point(class_scope:dzhyun.JPBShuJu)
 private:
  inline void set_has_daima();
  inline void clear_has_daima();
  inline void set_has_mingcheng();
  inline void clear_has_mingcheng();
  inline void set_has_shuxing();
  inline void clear_has_shuxing();
  inline void set_has_kuozhan();
  inline void clear_has_kuozhan();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr daima_;
  ::google::protobuf::internal::ArenaStringPtr mingcheng_;
  ::google::protobuf::internal::ArenaStringPtr shuxing_;
  ::google::protobuf::internal::ArenaStringPtr kuozhan_;
  friend void  protobuf_AddDesc_dzhyun_2ejianpanbao_2eproto();
  friend void protobuf_AssignDesc_dzhyun_2ejianpanbao_2eproto();
  friend void protobuf_ShutdownFile_dzhyun_2ejianpanbao_2eproto();

  void InitAsDefaultInstance();
  static JPBShuJu* default_instance_;
};
// -------------------------------------------------------------------

class JPBShuChu : public ::google::protobuf::Message {
 public:
  JPBShuChu();
  virtual ~JPBShuChu();

  JPBShuChu(const JPBShuChu& from);

  inline JPBShuChu& operator=(const JPBShuChu& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JPBShuChu& default_instance();

  void Swap(JPBShuChu* other);

  // implements Message ----------------------------------------------

  inline JPBShuChu* New() const { return New(NULL); }

  JPBShuChu* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JPBShuChu& from);
  void MergeFrom(const JPBShuChu& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JPBShuChu* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .dzhyun.JPBLeiXing LeiXing = 1;
  bool has_leixing() const;
  void clear_leixing();
  static const int kLeiXingFieldNumber = 1;
  ::dzhyun::JPBLeiXing leixing() const;
  void set_leixing(::dzhyun::JPBLeiXing value);

  // repeated .dzhyun.JPBShuJu ShuJu = 2;
  int shuju_size() const;
  void clear_shuju();
  static const int kShuJuFieldNumber = 2;
  const ::dzhyun::JPBShuJu& shuju(int index) const;
  ::dzhyun::JPBShuJu* mutable_shuju(int index);
  ::dzhyun::JPBShuJu* add_shuju();
  ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuJu >*
      mutable_shuju();
  const ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuJu >&
      shuju() const;

  // @@protoc_insertion_point(class_scope:dzhyun.JPBShuChu)
 private:
  inline void set_has_leixing();
  inline void clear_has_leixing();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuJu > shuju_;
  int leixing_;
  friend void  protobuf_AddDesc_dzhyun_2ejianpanbao_2eproto();
  friend void protobuf_AssignDesc_dzhyun_2ejianpanbao_2eproto();
  friend void protobuf_ShutdownFile_dzhyun_2ejianpanbao_2eproto();

  void InitAsDefaultInstance();
  static JPBShuChu* default_instance_;
};
// -------------------------------------------------------------------

class JianPanBaoShuChu : public ::google::protobuf::Message {
 public:
  JianPanBaoShuChu();
  virtual ~JianPanBaoShuChu();

  JianPanBaoShuChu(const JianPanBaoShuChu& from);

  inline JianPanBaoShuChu& operator=(const JianPanBaoShuChu& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JianPanBaoShuChu& default_instance();

  void Swap(JianPanBaoShuChu* other);

  // implements Message ----------------------------------------------

  inline JianPanBaoShuChu* New() const { return New(NULL); }

  JianPanBaoShuChu* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JianPanBaoShuChu& from);
  void MergeFrom(const JianPanBaoShuChu& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(JianPanBaoShuChu* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string GuanJianZi = 1;
  bool has_guanjianzi() const;
  void clear_guanjianzi();
  static const int kGuanJianZiFieldNumber = 1;
  const ::std::string& guanjianzi() const;
  void set_guanjianzi(const ::std::string& value);
  void set_guanjianzi(const char* value);
  void set_guanjianzi(const char* value, size_t size);
  ::std::string* mutable_guanjianzi();
  ::std::string* release_guanjianzi();
  void set_allocated_guanjianzi(::std::string* guanjianzi);

  // repeated .dzhyun.JPBShuChu JieGuo = 2;
  int jieguo_size() const;
  void clear_jieguo();
  static const int kJieGuoFieldNumber = 2;
  const ::dzhyun::JPBShuChu& jieguo(int index) const;
  ::dzhyun::JPBShuChu* mutable_jieguo(int index);
  ::dzhyun::JPBShuChu* add_jieguo();
  ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuChu >*
      mutable_jieguo();
  const ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuChu >&
      jieguo() const;

  // @@protoc_insertion_point(class_scope:dzhyun.JianPanBaoShuChu)
 private:
  inline void set_has_guanjianzi();
  inline void clear_has_guanjianzi();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr guanjianzi_;
  ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuChu > jieguo_;
  friend void  protobuf_AddDesc_dzhyun_2ejianpanbao_2eproto();
  friend void protobuf_AssignDesc_dzhyun_2ejianpanbao_2eproto();
  friend void protobuf_ShutdownFile_dzhyun_2ejianpanbao_2eproto();

  void InitAsDefaultInstance();
  static JianPanBaoShuChu* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// JPBShuJu

// required string DaiMa = 1;
inline bool JPBShuJu::has_daima() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JPBShuJu::set_has_daima() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JPBShuJu::clear_has_daima() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JPBShuJu::clear_daima() {
  daima_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_daima();
}
inline const ::std::string& JPBShuJu::daima() const {
  // @@protoc_insertion_point(field_get:dzhyun.JPBShuJu.DaiMa)
  return daima_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JPBShuJu::set_daima(const ::std::string& value) {
  set_has_daima();
  daima_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.JPBShuJu.DaiMa)
}
inline void JPBShuJu::set_daima(const char* value) {
  set_has_daima();
  daima_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.JPBShuJu.DaiMa)
}
inline void JPBShuJu::set_daima(const char* value, size_t size) {
  set_has_daima();
  daima_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.JPBShuJu.DaiMa)
}
inline ::std::string* JPBShuJu::mutable_daima() {
  set_has_daima();
  // @@protoc_insertion_point(field_mutable:dzhyun.JPBShuJu.DaiMa)
  return daima_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JPBShuJu::release_daima() {
  // @@protoc_insertion_point(field_release:dzhyun.JPBShuJu.DaiMa)
  clear_has_daima();
  return daima_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JPBShuJu::set_allocated_daima(::std::string* daima) {
  if (daima != NULL) {
    set_has_daima();
  } else {
    clear_has_daima();
  }
  daima_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), daima);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.JPBShuJu.DaiMa)
}

// required string MingCheng = 2;
inline bool JPBShuJu::has_mingcheng() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JPBShuJu::set_has_mingcheng() {
  _has_bits_[0] |= 0x00000002u;
}
inline void JPBShuJu::clear_has_mingcheng() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void JPBShuJu::clear_mingcheng() {
  mingcheng_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_mingcheng();
}
inline const ::std::string& JPBShuJu::mingcheng() const {
  // @@protoc_insertion_point(field_get:dzhyun.JPBShuJu.MingCheng)
  return mingcheng_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JPBShuJu::set_mingcheng(const ::std::string& value) {
  set_has_mingcheng();
  mingcheng_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.JPBShuJu.MingCheng)
}
inline void JPBShuJu::set_mingcheng(const char* value) {
  set_has_mingcheng();
  mingcheng_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.JPBShuJu.MingCheng)
}
inline void JPBShuJu::set_mingcheng(const char* value, size_t size) {
  set_has_mingcheng();
  mingcheng_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.JPBShuJu.MingCheng)
}
inline ::std::string* JPBShuJu::mutable_mingcheng() {
  set_has_mingcheng();
  // @@protoc_insertion_point(field_mutable:dzhyun.JPBShuJu.MingCheng)
  return mingcheng_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JPBShuJu::release_mingcheng() {
  // @@protoc_insertion_point(field_release:dzhyun.JPBShuJu.MingCheng)
  clear_has_mingcheng();
  return mingcheng_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JPBShuJu::set_allocated_mingcheng(::std::string* mingcheng) {
  if (mingcheng != NULL) {
    set_has_mingcheng();
  } else {
    clear_has_mingcheng();
  }
  mingcheng_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mingcheng);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.JPBShuJu.MingCheng)
}

// optional string ShuXing = 3;
inline bool JPBShuJu::has_shuxing() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void JPBShuJu::set_has_shuxing() {
  _has_bits_[0] |= 0x00000004u;
}
inline void JPBShuJu::clear_has_shuxing() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void JPBShuJu::clear_shuxing() {
  shuxing_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_shuxing();
}
inline const ::std::string& JPBShuJu::shuxing() const {
  // @@protoc_insertion_point(field_get:dzhyun.JPBShuJu.ShuXing)
  return shuxing_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JPBShuJu::set_shuxing(const ::std::string& value) {
  set_has_shuxing();
  shuxing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.JPBShuJu.ShuXing)
}
inline void JPBShuJu::set_shuxing(const char* value) {
  set_has_shuxing();
  shuxing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.JPBShuJu.ShuXing)
}
inline void JPBShuJu::set_shuxing(const char* value, size_t size) {
  set_has_shuxing();
  shuxing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.JPBShuJu.ShuXing)
}
inline ::std::string* JPBShuJu::mutable_shuxing() {
  set_has_shuxing();
  // @@protoc_insertion_point(field_mutable:dzhyun.JPBShuJu.ShuXing)
  return shuxing_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JPBShuJu::release_shuxing() {
  // @@protoc_insertion_point(field_release:dzhyun.JPBShuJu.ShuXing)
  clear_has_shuxing();
  return shuxing_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JPBShuJu::set_allocated_shuxing(::std::string* shuxing) {
  if (shuxing != NULL) {
    set_has_shuxing();
  } else {
    clear_has_shuxing();
  }
  shuxing_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shuxing);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.JPBShuJu.ShuXing)
}

// optional string KuoZhan = 4;
inline bool JPBShuJu::has_kuozhan() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void JPBShuJu::set_has_kuozhan() {
  _has_bits_[0] |= 0x00000008u;
}
inline void JPBShuJu::clear_has_kuozhan() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void JPBShuJu::clear_kuozhan() {
  kuozhan_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_kuozhan();
}
inline const ::std::string& JPBShuJu::kuozhan() const {
  // @@protoc_insertion_point(field_get:dzhyun.JPBShuJu.KuoZhan)
  return kuozhan_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JPBShuJu::set_kuozhan(const ::std::string& value) {
  set_has_kuozhan();
  kuozhan_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.JPBShuJu.KuoZhan)
}
inline void JPBShuJu::set_kuozhan(const char* value) {
  set_has_kuozhan();
  kuozhan_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.JPBShuJu.KuoZhan)
}
inline void JPBShuJu::set_kuozhan(const char* value, size_t size) {
  set_has_kuozhan();
  kuozhan_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.JPBShuJu.KuoZhan)
}
inline ::std::string* JPBShuJu::mutable_kuozhan() {
  set_has_kuozhan();
  // @@protoc_insertion_point(field_mutable:dzhyun.JPBShuJu.KuoZhan)
  return kuozhan_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JPBShuJu::release_kuozhan() {
  // @@protoc_insertion_point(field_release:dzhyun.JPBShuJu.KuoZhan)
  clear_has_kuozhan();
  return kuozhan_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JPBShuJu::set_allocated_kuozhan(::std::string* kuozhan) {
  if (kuozhan != NULL) {
    set_has_kuozhan();
  } else {
    clear_has_kuozhan();
  }
  kuozhan_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), kuozhan);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.JPBShuJu.KuoZhan)
}

// -------------------------------------------------------------------

// JPBShuChu

// required .dzhyun.JPBLeiXing LeiXing = 1;
inline bool JPBShuChu::has_leixing() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JPBShuChu::set_has_leixing() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JPBShuChu::clear_has_leixing() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JPBShuChu::clear_leixing() {
  leixing_ = 0;
  clear_has_leixing();
}
inline ::dzhyun::JPBLeiXing JPBShuChu::leixing() const {
  // @@protoc_insertion_point(field_get:dzhyun.JPBShuChu.LeiXing)
  return static_cast< ::dzhyun::JPBLeiXing >(leixing_);
}
inline void JPBShuChu::set_leixing(::dzhyun::JPBLeiXing value) {
  assert(::dzhyun::JPBLeiXing_IsValid(value));
  set_has_leixing();
  leixing_ = value;
  // @@protoc_insertion_point(field_set:dzhyun.JPBShuChu.LeiXing)
}

// repeated .dzhyun.JPBShuJu ShuJu = 2;
inline int JPBShuChu::shuju_size() const {
  return shuju_.size();
}
inline void JPBShuChu::clear_shuju() {
  shuju_.Clear();
}
inline const ::dzhyun::JPBShuJu& JPBShuChu::shuju(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.JPBShuChu.ShuJu)
  return shuju_.Get(index);
}
inline ::dzhyun::JPBShuJu* JPBShuChu::mutable_shuju(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.JPBShuChu.ShuJu)
  return shuju_.Mutable(index);
}
inline ::dzhyun::JPBShuJu* JPBShuChu::add_shuju() {
  // @@protoc_insertion_point(field_add:dzhyun.JPBShuChu.ShuJu)
  return shuju_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuJu >*
JPBShuChu::mutable_shuju() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.JPBShuChu.ShuJu)
  return &shuju_;
}
inline const ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuJu >&
JPBShuChu::shuju() const {
  // @@protoc_insertion_point(field_list:dzhyun.JPBShuChu.ShuJu)
  return shuju_;
}

// -------------------------------------------------------------------

// JianPanBaoShuChu

// required string GuanJianZi = 1;
inline bool JianPanBaoShuChu::has_guanjianzi() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JianPanBaoShuChu::set_has_guanjianzi() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JianPanBaoShuChu::clear_has_guanjianzi() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JianPanBaoShuChu::clear_guanjianzi() {
  guanjianzi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_guanjianzi();
}
inline const ::std::string& JianPanBaoShuChu::guanjianzi() const {
  // @@protoc_insertion_point(field_get:dzhyun.JianPanBaoShuChu.GuanJianZi)
  return guanjianzi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JianPanBaoShuChu::set_guanjianzi(const ::std::string& value) {
  set_has_guanjianzi();
  guanjianzi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.JianPanBaoShuChu.GuanJianZi)
}
inline void JianPanBaoShuChu::set_guanjianzi(const char* value) {
  set_has_guanjianzi();
  guanjianzi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.JianPanBaoShuChu.GuanJianZi)
}
inline void JianPanBaoShuChu::set_guanjianzi(const char* value, size_t size) {
  set_has_guanjianzi();
  guanjianzi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.JianPanBaoShuChu.GuanJianZi)
}
inline ::std::string* JianPanBaoShuChu::mutable_guanjianzi() {
  set_has_guanjianzi();
  // @@protoc_insertion_point(field_mutable:dzhyun.JianPanBaoShuChu.GuanJianZi)
  return guanjianzi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JianPanBaoShuChu::release_guanjianzi() {
  // @@protoc_insertion_point(field_release:dzhyun.JianPanBaoShuChu.GuanJianZi)
  clear_has_guanjianzi();
  return guanjianzi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JianPanBaoShuChu::set_allocated_guanjianzi(::std::string* guanjianzi) {
  if (guanjianzi != NULL) {
    set_has_guanjianzi();
  } else {
    clear_has_guanjianzi();
  }
  guanjianzi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), guanjianzi);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.JianPanBaoShuChu.GuanJianZi)
}

// repeated .dzhyun.JPBShuChu JieGuo = 2;
inline int JianPanBaoShuChu::jieguo_size() const {
  return jieguo_.size();
}
inline void JianPanBaoShuChu::clear_jieguo() {
  jieguo_.Clear();
}
inline const ::dzhyun::JPBShuChu& JianPanBaoShuChu::jieguo(int index) const {
  // @@protoc_insertion_point(field_get:dzhyun.JianPanBaoShuChu.JieGuo)
  return jieguo_.Get(index);
}
inline ::dzhyun::JPBShuChu* JianPanBaoShuChu::mutable_jieguo(int index) {
  // @@protoc_insertion_point(field_mutable:dzhyun.JianPanBaoShuChu.JieGuo)
  return jieguo_.Mutable(index);
}
inline ::dzhyun::JPBShuChu* JianPanBaoShuChu::add_jieguo() {
  // @@protoc_insertion_point(field_add:dzhyun.JianPanBaoShuChu.JieGuo)
  return jieguo_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuChu >*
JianPanBaoShuChu::mutable_jieguo() {
  // @@protoc_insertion_point(field_mutable_list:dzhyun.JianPanBaoShuChu.JieGuo)
  return &jieguo_;
}
inline const ::google::protobuf::RepeatedPtrField< ::dzhyun::JPBShuChu >&
JianPanBaoShuChu::jieguo() const {
  // @@protoc_insertion_point(field_list:dzhyun.JianPanBaoShuChu.JieGuo)
  return jieguo_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dzhyun

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::dzhyun::JPBLeiXing> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::dzhyun::JPBLeiXing>() {
  return ::dzhyun::JPBLeiXing_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dzhyun_2ejianpanbao_2eproto__INCLUDED
