// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.sysmsg.proto

#ifndef PROTOBUF_dzhyun_2esysmsg_2eproto__INCLUDED
#define PROTOBUF_dzhyun_2esysmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dzhyun {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_dzhyun_2esysmsg_2eproto();
void protobuf_AssignDesc_dzhyun_2esysmsg_2eproto();
void protobuf_ShutdownFile_dzhyun_2esysmsg_2eproto();

class XiTongXiaoXi;

// ===================================================================

class XiTongXiaoXi : public ::google::protobuf::Message {
 public:
  XiTongXiaoXi();
  virtual ~XiTongXiaoXi();

  XiTongXiaoXi(const XiTongXiaoXi& from);

  inline XiTongXiaoXi& operator=(const XiTongXiaoXi& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const XiTongXiaoXi& default_instance();

  void Swap(XiTongXiaoXi* other);

  // implements Message ----------------------------------------------

  inline XiTongXiaoXi* New() const { return New(NULL); }

  XiTongXiaoXi* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const XiTongXiaoXi& from);
  void MergeFrom(const XiTongXiaoXi& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(XiTongXiaoXi* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string LeiXing = 1;
  bool has_leixing() const;
  void clear_leixing();
  static const int kLeiXingFieldNumber = 1;
  const ::std::string& leixing() const;
  void set_leixing(const ::std::string& value);
  void set_leixing(const char* value);
  void set_leixing(const char* value, size_t size);
  ::std::string* mutable_leixing();
  ::std::string* release_leixing();
  void set_allocated_leixing(::std::string* leixing);

  // optional string ShuJu = 2;
  bool has_shuju() const;
  void clear_shuju();
  static const int kShuJuFieldNumber = 2;
  const ::std::string& shuju() const;
  void set_shuju(const ::std::string& value);
  void set_shuju(const char* value);
  void set_shuju(const char* value, size_t size);
  ::std::string* mutable_shuju();
  ::std::string* release_shuju();
  void set_allocated_shuju(::std::string* shuju);

  // @@protoc_insertion_point(class_scope:dzhyun.XiTongXiaoXi)
 private:
  inline void set_has_leixing();
  inline void clear_has_leixing();
  inline void set_has_shuju();
  inline void clear_has_shuju();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr leixing_;
  ::google::protobuf::internal::ArenaStringPtr shuju_;
  friend void  protobuf_AddDesc_dzhyun_2esysmsg_2eproto();
  friend void protobuf_AssignDesc_dzhyun_2esysmsg_2eproto();
  friend void protobuf_ShutdownFile_dzhyun_2esysmsg_2eproto();

  void InitAsDefaultInstance();
  static XiTongXiaoXi* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// XiTongXiaoXi

// optional string LeiXing = 1;
inline bool XiTongXiaoXi::has_leixing() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void XiTongXiaoXi::set_has_leixing() {
  _has_bits_[0] |= 0x00000001u;
}
inline void XiTongXiaoXi::clear_has_leixing() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void XiTongXiaoXi::clear_leixing() {
  leixing_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_leixing();
}
inline const ::std::string& XiTongXiaoXi::leixing() const {
  // @@protoc_insertion_point(field_get:dzhyun.XiTongXiaoXi.LeiXing)
  return leixing_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XiTongXiaoXi::set_leixing(const ::std::string& value) {
  set_has_leixing();
  leixing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.XiTongXiaoXi.LeiXing)
}
inline void XiTongXiaoXi::set_leixing(const char* value) {
  set_has_leixing();
  leixing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.XiTongXiaoXi.LeiXing)
}
inline void XiTongXiaoXi::set_leixing(const char* value, size_t size) {
  set_has_leixing();
  leixing_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.XiTongXiaoXi.LeiXing)
}
inline ::std::string* XiTongXiaoXi::mutable_leixing() {
  set_has_leixing();
  // @@protoc_insertion_point(field_mutable:dzhyun.XiTongXiaoXi.LeiXing)
  return leixing_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XiTongXiaoXi::release_leixing() {
  // @@protoc_insertion_point(field_release:dzhyun.XiTongXiaoXi.LeiXing)
  clear_has_leixing();
  return leixing_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XiTongXiaoXi::set_allocated_leixing(::std::string* leixing) {
  if (leixing != NULL) {
    set_has_leixing();
  } else {
    clear_has_leixing();
  }
  leixing_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), leixing);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.XiTongXiaoXi.LeiXing)
}

// optional string ShuJu = 2;
inline bool XiTongXiaoXi::has_shuju() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void XiTongXiaoXi::set_has_shuju() {
  _has_bits_[0] |= 0x00000002u;
}
inline void XiTongXiaoXi::clear_has_shuju() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void XiTongXiaoXi::clear_shuju() {
  shuju_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_shuju();
}
inline const ::std::string& XiTongXiaoXi::shuju() const {
  // @@protoc_insertion_point(field_get:dzhyun.XiTongXiaoXi.ShuJu)
  return shuju_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XiTongXiaoXi::set_shuju(const ::std::string& value) {
  set_has_shuju();
  shuju_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dzhyun.XiTongXiaoXi.ShuJu)
}
inline void XiTongXiaoXi::set_shuju(const char* value) {
  set_has_shuju();
  shuju_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dzhyun.XiTongXiaoXi.ShuJu)
}
inline void XiTongXiaoXi::set_shuju(const char* value, size_t size) {
  set_has_shuju();
  shuju_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dzhyun.XiTongXiaoXi.ShuJu)
}
inline ::std::string* XiTongXiaoXi::mutable_shuju() {
  set_has_shuju();
  // @@protoc_insertion_point(field_mutable:dzhyun.XiTongXiaoXi.ShuJu)
  return shuju_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* XiTongXiaoXi::release_shuju() {
  // @@protoc_insertion_point(field_release:dzhyun.XiTongXiaoXi.ShuJu)
  clear_has_shuju();
  return shuju_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void XiTongXiaoXi::set_allocated_shuju(::std::string* shuju) {
  if (shuju != NULL) {
    set_has_shuju();
  } else {
    clear_has_shuju();
  }
  shuju_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shuju);
  // @@protoc_insertion_point(field_set_allocated:dzhyun.XiTongXiaoXi.ShuJu)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace dzhyun

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dzhyun_2esysmsg_2eproto__INCLUDED
